CREATE TABLE theme_profiles
(
    id          text        PRIMARY KEY,
    name        text        NOT NULL,
    description text        NOT NULL DEFAULT '',
    tokens      jsonb       NOT NULL CHECK (jsonb_typeof(tokens) = 'object'),
    built_in    boolean     NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (name)
);

CREATE TABLE theme_settings
(
    id                boolean     PRIMARY KEY DEFAULT true CHECK (id),
    active_profile_id text        NOT NULL REFERENCES theme_profiles (id),
    updated_at         timestamptz NOT NULL DEFAULT now()
);

INSERT INTO theme_profiles (id, name, description, tokens, built_in)
VALUES
    (
        'varka-dark',
        'Varka Dark',
        'Default dark frontend theme.',
        jsonb_build_object(
            '--bg', '#101416',
            '--surface', '#161b1e',
            '--surface-2', '#1b2125',
            '--surface-3', '#222a2f',
            '--surface-high', '#2b343a',
            '--surface-contrast', '#13181b',
            '--panel', '#1b2125',
            '--panel-2', '#222a2f',
            '--panel-3', '#303a40',
            '--input-bg', '#151b1e',
            '--canvas-bg', '#111719',
            '--node-bg', '#1d2629',
            '--node-border', '#435057',
            '--border', '#3b484f',
            '--border-subtle', '#283238',
            '--outline', '#7f929b',
            '--outline-soft', 'rgba(141, 160, 168, 0.2)',
            '--text', '#e4ecec',
            '--text-strong', '#f8fbfa',
            '--muted', '#aebdc0',
            '--muted-2', '#83949a',
            '--text-soft', '#cad5d6',
            '--node-title', '#d5dfdf',
            '--accent', '#00a6e0',
            '--accent-dark', '#0078ac',
            '--accent-light', '#7bd0ff',
            '--accent-glow', 'rgba(0, 166, 224, 0.28)',
            '--accent-select', '#5ecbff',
            '--accent-2', '#d6b36f',
            '--danger', '#f27878',
            '--danger-dark', '#c95151',
            '--success', '#53c993',
            '--warning', '#d7a64e',
            '--chat-user-bg', '#008bc4',
            '--chat-user-text', '#f2fbff',
            '--chat-assistant-bg', '#1f282c',
            '--chat-assistant-border', '#39484e',
            '--grid-line-major', 'rgba(149, 168, 170, 0.16)',
            '--grid-line-minor', 'rgba(149, 168, 170, 0.07)',
            '--canvas-dot', 'rgb(105 125 127 / 0.36)'
        ),
        true
    ),
    (
        'varka-light',
        'Varka Light',
        'Default light frontend theme.',
        jsonb_build_object(
            '--bg', '#edf3fa',
            '--surface', '#ffffff',
            '--surface-2', '#f7f9fc',
            '--surface-3', '#edf2f8',
            '--surface-high', '#e3ebf5',
            '--surface-contrast', '#f4f7fb',
            '--panel', '#f7f9fc',
            '--panel-2', '#edf2f8',
            '--panel-3', '#e2e9f3',
            '--input-bg', '#ffffff',
            '--canvas-bg', '#f8fbff',
            '--node-bg', '#ffffff',
            '--node-border', '#c2cfdf',
            '--border', '#c6d2e2',
            '--border-subtle', '#d7e0ec',
            '--outline', '#70829b',
            '--outline-soft', 'rgba(112, 130, 155, 0.2)',
            '--text', '#1f2733',
            '--text-strong', '#111926',
            '--muted', '#5f6f84',
            '--muted-2', '#7a8aa0',
            '--text-soft', '#3b4656',
            '--node-title', '#44546d',
            '--accent', '#0077a8',
            '--accent-dark', '#005f89',
            '--accent-light', '#008dc8',
            '--accent-glow', 'rgba(0, 119, 168, 0.2)',
            '--accent-select', '#0c9bd6',
            '--accent-2', '#8c6b3f',
            '--danger', '#be3636',
            '--danger-dark', '#982727',
            '--success', '#0f8e6e',
            '--warning', '#aa7215',
            '--chat-user-bg', '#0077a8',
            '--chat-user-text', '#ffffff',
            '--chat-assistant-bg', '#f2f6fb',
            '--chat-assistant-border', '#cfd9e6',
            '--grid-line-major', 'rgba(81, 99, 126, 0.12)',
            '--grid-line-minor', 'rgba(81, 99, 126, 0.05)',
            '--canvas-dot', 'rgba(113, 130, 155, 0.35)'
        ),
        true
    ),
    (
        'admin-green',
        'Admin Green',
        'Frontend profile derived from the admin control plane theme.',
        jsonb_build_object(
            '--bg', '#f6f7f4',
            '--surface', '#ffffff',
            '--surface-2', '#fbfcfa',
            '--surface-3', '#edf3ef',
            '--surface-high', '#e4f4eb',
            '--surface-contrast', '#f9faf8',
            '--panel', '#ffffff',
            '--panel-2', '#fbfcfa',
            '--panel-3', '#edf3ef',
            '--input-bg', '#ffffff',
            '--canvas-bg', '#f5f7f4',
            '--node-bg', '#ffffff',
            '--node-border', '#dce2dc',
            '--border', '#d7ded7',
            '--border-subtle', '#edf0ed',
            '--outline', '#68756f',
            '--outline-soft', 'rgba(13, 111, 84, 0.12)',
            '--text', '#16201b',
            '--text-strong', '#16201b',
            '--muted', '#65726c',
            '--muted-2', '#77837c',
            '--text-soft', '#26352f',
            '--node-title', '#184c3c',
            '--accent', '#0d6f54',
            '--accent-dark', '#104934',
            '--accent-light', '#245646',
            '--accent-glow', 'rgba(13, 111, 84, 0.16)',
            '--accent-select', '#235344',
            '--accent-2', '#725100',
            '--danger', '#b42318',
            '--danger-dark', '#842029',
            '--success', '#0d5d42',
            '--warning', '#725100',
            '--chat-user-bg', '#0d6f54',
            '--chat-user-text', '#ffffff',
            '--chat-assistant-bg', '#fbfcfa',
            '--chat-assistant-border', '#dce2dc',
            '--grid-line-major', 'rgba(101, 114, 108, 0.16)',
            '--grid-line-minor', 'rgba(101, 114, 108, 0.07)',
            '--canvas-dot', 'rgba(13, 111, 84, 0.24)'
        ),
        true
    );

INSERT INTO theme_settings (id, active_profile_id)
VALUES (true, 'varka-dark');
