<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
  xmlns:xmi="http://www.omg.org/XMI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  name="kernel" nsPrefix="kernel"
  nsURI="https://modless.org/kernel/1.0" xmi:version="2.0">
  <eClassifiers name="Priority" xsi:type="ecore:EEnum">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
    <eLiterals name="CRITICAL" value="3"/>
  </eClassifiers>
  <eClassifiers name="Severity" xsi:type="ecore:EEnum">
    <eLiterals name="INFO"/>
    <eLiterals name="WARNING" value="1"/>
    <eLiterals name="ERROR" value="2"/>
    <eLiterals name="CRITICAL" value="3"/>
    <eLiterals name="BLOCKER" value="4"/>
  </eClassifiers>
  <eClassifiers name="ConstraintStrength" xsi:type="ecore:EEnum">
    <eLiterals name="ADVISORY"/>
    <eLiterals name="RECOMMENDED" value="1"/>
    <eLiterals name="MANDATORY" value="2"/>
    <eLiterals name="BLOCKING" value="3"/>
  </eClassifiers>
  <eClassifiers name="LifecycleStatus" xsi:type="ecore:EEnum">
    <eLiterals name="DRAFT"/>
    <eLiterals name="INCOMPLETE" value="1"/>
    <eLiterals name="REVIEW_REQUIRED" value="2"/>
    <eLiterals name="APPROVED" value="3"/>
    <eLiterals name="TRANSFORMATION_READY" value="4"/>
    <eLiterals name="DEPLOYMENT_READY" value="5"/>
    <eLiterals name="PRODUCTION_READY" value="6"/>
    <eLiterals name="BLOCKED" value="7"/>
    <eLiterals name="DEPRECATED" value="8"/>
  </eClassifiers>
  <eClassifiers name="TraceConfidence" xsi:type="ecore:EEnum">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
    <eLiterals name="VERIFIED" value="3"/>
    <eLiterals name="MANUAL" value="4"/>
  </eClassifiers>
  <eClassifiers name="TraceLinkType" xsi:type="ecore:EEnum">
    <eLiterals name="DERIVES_FROM"/>
    <eLiterals name="REFINES" value="1"/>
    <eLiterals name="SATISFIES" value="2"/>
    <eLiterals name="CONSTRAINS" value="3"/>
    <eLiterals name="GENERATED_FROM" value="4"/>
    <eLiterals name="VALIDATES" value="5"/>
    <eLiterals name="MITIGATES" value="6"/>
    <eLiterals name="CONFLICTS_WITH" value="7"/>
    <eLiterals name="MAPS_TO" value="8"/>
    <eLiterals name="TRANSFORMS_TO" value="9"/>
    <eLiterals name="REALIZES" value="10"/>
    <eLiterals name="IMPLEMENTS" value="11"/>
    <eLiterals name="DEPLOYS_TO" value="12"/>
    <eLiterals name="OBSERVES" value="13"/>
    <eLiterals name="OTHER" value="14"/>
  </eClassifiers>
  <eClassifiers name="FindingType" xsi:type="ecore:EEnum">
    <eLiterals name="MISSING_INFORMATION"/>
    <eLiterals name="INCONSISTENCY" value="1"/>
    <eLiterals name="BLOCKING_RISK" value="2"/>
    <eLiterals name="BLOCKING_HOTSPOT" value="3"/>
    <eLiterals name="VALIDATION_WARNING" value="4"/>
    <eLiterals name="VALIDATION_ERROR" value="5"/>
    <eLiterals name="TRANSFORMATION_ASSUMPTION" value="6"/>
    <eLiterals name="POLICY_VIOLATION" value="7"/>
    <eLiterals name="SECURITY_RISK" value="8"/>
    <eLiterals name="DEPLOYMENT_RISK" value="9"/>
    <eLiterals name="OTHER" value="10"/>
  </eClassifiers>
  <eClassifiers name="StructuredFormat" xsi:type="ecore:EEnum">
    <eLiterals name="TEXT"/>
    <eLiterals name="JSON" value="1"/>
    <eLiterals name="YAML" value="2"/>
    <eLiterals name="TOML" value="3"/>
    <eLiterals name="XML" value="4"/>
    <eLiterals name="MARKDOWN" value="5"/>
    <eLiterals name="ASL_JSON" value="6"/>
    <eLiterals name="IAM_POLICY_JSON" value="7"/>
    <eLiterals name="CLOUDFORMATION_INTRINSIC" value="8"/>
    <eLiterals name="OTHER" value="9"/>
  </eClassifiers>
  <eClassifiers name="ExpressionLanguage" xsi:type="ecore:EEnum">
    <eLiterals name="NATURAL_LANGUAGE"/>
    <eLiterals name="OCL" value="1"/>
    <eLiterals name="FEEL" value="2"/>
    <eLiterals name="JSONPATH" value="3"/>
    <eLiterals name="JSONATA" value="4"/>
    <eLiterals name="JAVASCRIPT" value="5"/>
    <eLiterals name="TYPESCRIPT" value="6"/>
    <eLiterals name="PYTHON" value="7"/>
    <eLiterals name="SQL" value="8"/>
    <eLiterals name="REGEX" value="9"/>
    <eLiterals name="OTHER" value="10"/>
  </eClassifiers>
  <eClassifiers name="ExpressionPhase" xsi:type="ecore:EEnum">
    <eLiterals name="DESIGN_TIME"/>
    <eLiterals name="VALIDATION_TIME" value="1"/>
    <eLiterals name="RUNTIME" value="2"/>
    <eLiterals name="GENERATION_TIME" value="3"/>
  </eClassifiers>
  <eClassifiers interface="true" name="DeployableElement" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="InvocationSource" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="InvocationTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="FunctionTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="WorkflowTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="SubscriptionTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="RoutingTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="FlowEndpoint" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="ProtectedResource" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="PolicyTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="DataAccessTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="ExternalCallTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="EnvironmentTarget" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="CredentialRequirementLike" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="RouteEndpoint" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="EventCarrier" xsi:type="ecore:EClass"/>
  <eClassifiers interface="true" name="ConfigurableElement" xsi:type="ecore:EClass"/>
  <eClassifiers name="KeyValue" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      lowerBound="1" name="key"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="value"
      xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//KeyValue" name="Annotation" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="source"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures changeable="false" eOpposite="#//ModelElement/annotations"
      eType="#//ModelElement"
      lowerBound="1"
      name="owner" transient="true" xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers abstract="true" name="ModelElement" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      iD="true" lowerBound="1"
      name="id"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="name"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="summary"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="description"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="documentation"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="modelTags" upperBound="-1"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="externalId"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//LifecycleStatus" name="lifecycleStatus"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures containment="true" eOpposite="#//Annotation/owner" eType="#//Annotation"
      name="annotations" upperBound="-1" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eOpposite="#//TraceLink/target" eType="#//TraceLink" name="incomingTraces"
      upperBound="-1" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eOpposite="#//TraceLink/source" eType="#//TraceLink" name="outgoingTraces"
      upperBound="-1" xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers abstract="true" eSuperTypes="#//ModelElement" name="NamedModelElement"
    xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      lowerBound="1" name="displayName"
      xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers abstract="true" eSuperTypes="#//ModelElement" name="TraceableElement"
    xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="sourceReference"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="sourceExcerpt"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="sourceQualifiedName"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="sourceUri"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="sourceLine"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="traceId"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="generatedFrom"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="generatedByTransformation"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="rationale"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="reviewStatus"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="reviewNotes"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="manuallyMaintained"
      xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers abstract="true" eSuperTypes="#//TraceableElement" name="SemanticRelationship"
    xsi:type="ecore:EClass"/>
  <eClassifiers eSuperTypes="#//TraceableElement" name="Multiplicity" xsi:type="ecore:EClass">
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject" lowerBound="1"
      name="lowerBound"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
      name="upperBound"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="unbounded"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject" name="ordered"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures defaultValueLiteral="true"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="unique"
      xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="Cardinality" xsi:type="ecore:EClass">
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
      name="lowerBound"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
      name="upperBound"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="unbounded"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject" name="ordered"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures defaultValueLiteral="true"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="unique"
      xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="Expression" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//ExpressionLanguage" lowerBound="1" name="language"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      lowerBound="1" name="body"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//ExpressionPhase" name="phase" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="sideEffectFree"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//ModelElement" name="referencedElements" upperBound="-1"
      xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="TraceModel" xsi:type="ecore:EClass">
    <eStructuralFeatures containment="true" eOpposite="#//TraceLink/traceModel" eType="#//TraceLink"
      name="links" upperBound="-1" xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="TraceLink" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//TraceLinkType" lowerBound="1" name="linkType"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="transformationRule"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//TraceConfidence" lowerBound="1" name="confidence"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="confidenceRationale"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"
      name="confidenceScore"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="sourceElementId"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="targetElementId"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures changeable="false" eOpposite="#//TraceModel/links" eType="#//TraceModel"
      lowerBound="1" name="traceModel" transient="true" xsi:type="ecore:EReference"/>
    <eStructuralFeatures eOpposite="#//ModelElement/outgoingTraces" eType="#//ModelElement"
      name="source"
      xsi:type="ecore:EReference"/>
    <eStructuralFeatures eOpposite="#//ModelElement/incomingTraces" eType="#//ModelElement"
      name="target"
      xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers abstract="true" eSuperTypes="#//TraceableElement" name="TransformationAssumption"
    xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="assumptionStatement"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="validationApproach"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject" name="accepted"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="acceptedBy"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
      name="acceptedOn"
      xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="StructuredDocument" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//StructuredFormat" lowerBound="1" name="format"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="content"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="externalUri"
      xsi:type="ecore:EAttribute"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="ProductionReadinessAssessment"
    xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//LifecycleStatus" name="readinessStatus"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
      name="assessedAt"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="assessedBy"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="transformationReady"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="deploymentReady"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
      name="productionReady"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures containment="true" eOpposite="#//ReadinessFinding/assessment"
      eType="#//ReadinessFinding"
      name="findings" upperBound="-1" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eOpposite="#//ReadinessCheck/assessment"
      eType="#//ReadinessCheck"
      name="checks" upperBound="-1" xsi:type="ecore:EReference"/>
    <eStructuralFeatures containment="true" eOpposite="#//ManualDecision/assessment"
      eType="#//ManualDecision"
      name="manualDecisions" upperBound="-1" xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="ReadinessFinding" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="#//FindingType" name="findingType" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//Severity" lowerBound="1" name="severity"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="ruleId"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="message"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="recommendation"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject" name="blocking"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures changeable="false" eOpposite="#//ProductionReadinessAssessment/findings"
      eType="#//ProductionReadinessAssessment"
      lowerBound="1" name="assessment" transient="true"
      xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//ModelElement" name="affectedElements" upperBound="-1"
      xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="ReadinessCheck" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      lowerBound="1" name="checkId"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//Severity" lowerBound="1" name="severity"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject" name="passed"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="message"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="remediation"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures changeable="false" eOpposite="#//ProductionReadinessAssessment/checks"
      eType="#//ProductionReadinessAssessment"
      lowerBound="1" name="assessment" transient="true"
      xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//ModelElement" name="affectedElements" upperBound="-1"
      xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers eSuperTypes="#//TraceableElement" name="ManualDecision" xsi:type="ecore:EClass">
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      lowerBound="1" name="question"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="decision"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
      name="decisionOwner"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
      name="dueDate"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject" name="blocking"
      xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures eType="#//Severity" name="severity" xsi:type="ecore:EAttribute"/>
    <eStructuralFeatures changeable="false"
      eOpposite="#//ProductionReadinessAssessment/manualDecisions"
      eType="#//ProductionReadinessAssessment"
      name="assessment" transient="true"
      xsi:type="ecore:EReference"/>
    <eStructuralFeatures eType="#//ModelElement" name="affectedElements" upperBound="-1"
      xsi:type="ecore:EReference"/>
  </eClassifiers>
</ecore:EPackage>
