<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kernel" nsURI="https://modless.org/kernel/1.0" nsPrefix="kernel">
  <eClassifiers xsi:type="ecore:EEnum" name="Priority">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
    <eLiterals name="CRITICAL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Severity">
    <eLiterals name="INFO"/>
    <eLiterals name="WARNING" value="1"/>
    <eLiterals name="ERROR" value="2"/>
    <eLiterals name="CRITICAL" value="3"/>
    <eLiterals name="BLOCKER" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintStrength">
    <eLiterals name="ADVISORY"/>
    <eLiterals name="RECOMMENDED" value="1"/>
    <eLiterals name="MANDATORY" value="2"/>
    <eLiterals name="BLOCKING" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LifecycleStatus">
    <eLiterals name="DRAFT"/>
    <eLiterals name="INCOMPLETE" value="1"/>
    <eLiterals name="REVIEW_REQUIRED" value="2"/>
    <eLiterals name="REVIEW_READY" value="3"/>
    <eLiterals name="REVIEWABLE" value="4"/>
    <eLiterals name="TRANSFORMATION_READY" value="5"/>
    <eLiterals name="DEPLOYMENT_READY" value="6"/>
    <eLiterals name="PRODUCTION_READY" value="7"/>
    <eLiterals name="BLOCKED" value="8"/>
    <eLiterals name="DEPRECATED" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TraceLinkType">
    <eLiterals name="DERIVES_FROM"/>
    <eLiterals name="REFINES" value="1"/>
    <eLiterals name="SATISFIES" value="2"/>
    <eLiterals name="CONSTRAINS" value="3"/>
    <eLiterals name="GENERATED_FROM" value="4"/>
    <eLiterals name="VALIDATES" value="5"/>
    <eLiterals name="MITIGATES" value="6"/>
    <eLiterals name="CONFLICTS_WITH" value="7"/>
    <eLiterals name="MAPS_TO" value="8"/>
    <eLiterals name="TRANSFORMS_TO" value="9"/>
    <eLiterals name="REALIZES" value="10"/>
    <eLiterals name="IMPLEMENTS" value="11"/>
    <eLiterals name="DEPLOYS_TO" value="12"/>
    <eLiterals name="OBSERVES" value="13"/>
    <eLiterals name="OTHER" value="14"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FindingType">
    <eLiterals name="MISSING_INFORMATION"/>
    <eLiterals name="INCONSISTENCY" value="1"/>
    <eLiterals name="BLOCKING_RISK" value="2"/>
    <eLiterals name="BLOCKING_HOTSPOT" value="3"/>
    <eLiterals name="VALIDATION_WARNING" value="4"/>
    <eLiterals name="VALIDATION_ERROR" value="5"/>
    <eLiterals name="TRANSFORMATION_ASSUMPTION" value="6"/>
    <eLiterals name="POLICY_VIOLATION" value="7"/>
    <eLiterals name="SECURITY_RISK" value="8"/>
    <eLiterals name="DEPLOYMENT_RISK" value="9"/>
    <eLiterals name="OTHER" value="10"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StructuredFormat">
    <eLiterals name="TEXT"/>
    <eLiterals name="JSON" value="1"/>
    <eLiterals name="YAML" value="2"/>
    <eLiterals name="TOML" value="3"/>
    <eLiterals name="XML" value="4"/>
    <eLiterals name="MARKDOWN" value="5"/>
    <eLiterals name="ASL_JSON" value="6"/>
    <eLiterals name="IAM_POLICY_JSON" value="7"/>
    <eLiterals name="CLOUDFORMATION_INTRINSIC" value="8"/>
    <eLiterals name="OTHER" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployableElement" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationSource" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvocationTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SubscriptionTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoutingTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FlowEndpoint" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProtectedResource" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataAccessTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalCallTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentTarget" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CredentialRequirementLike" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="RouteEndpoint" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EventCarrier" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation" eSuperTypes="#//KeyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" lowerBound="1" eType="#//ModelElement"
        changeable="false" transient="true" eOpposite="#//ModelElement/annotations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="documentation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelTags" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lifecycleStatus" eType="#//LifecycleStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="#//Annotation" containment="true" eOpposite="#//Annotation/owner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingTraces" upperBound="-1"
        eType="#//TraceLink" eOpposite="#//TraceLink/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingTraces" upperBound="-1"
        eType="#//TraceLink" eOpposite="#//TraceLink/source"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceableElement" abstract="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceReference" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceExcerpt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceQualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="traceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedFrom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generatedByTransformation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rationale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reviewStatus" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reviewNotes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="manuallyMaintained" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticRelationship" abstract="true"
      eSuperTypes="#//TraceableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TraceModel" eSuperTypes="#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//TraceLink" containment="true" eOpposite="#//TraceLink/traceModel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceLink" eSuperTypes="#//TraceableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="TraceLinkHasReferenceOrExternalId"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkType" lowerBound="1"
        eType="#//TraceLinkType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationRule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confidence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceElementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetElementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="traceModel" lowerBound="1"
        eType="#//TraceModel" changeable="false" transient="true" eOpposite="#//TraceModel/links"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ModelElement"
        eOpposite="#//ModelElement/outgoingTraces"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ModelElement"
        eOpposite="#//ModelElement/incomingTraces"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationAssumption" abstract="true"
      eSuperTypes="#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assumptionStatement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validationApproach" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accepted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptedBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptedOn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StructuredDocument" eSuperTypes="#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="format" lowerBound="1"
        eType="#//StructuredFormat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalUri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductionReadinessAssessment" eSuperTypes="#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readinessStatus" eType="#//LifecycleStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assessedAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assessedBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationReady" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deploymentReady" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="productionReady" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="findings" upperBound="-1"
        eType="#//ReadinessFinding" containment="true" eOpposite="#//ReadinessFinding/assessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checks" upperBound="-1"
        eType="#//ReadinessCheck" containment="true" eOpposite="#//ReadinessCheck/assessment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manualDecisions" upperBound="-1"
        eType="#//ManualDecision" containment="true" eOpposite="#//ManualDecision/assessment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadinessFinding" eSuperTypes="#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="findingType" eType="#//FindingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" lowerBound="1"
        eType="#//Severity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recommendation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assessment" lowerBound="1"
        eType="#//ProductionReadinessAssessment" changeable="false" transient="true"
        eOpposite="#//ProductionReadinessAssessment/findings"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedElements" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadinessCheck" eSuperTypes="#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkId" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" lowerBound="1"
        eType="#//Severity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="remediation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assessment" lowerBound="1"
        eType="#//ProductionReadinessAssessment" changeable="false" transient="true"
        eOpposite="#//ProductionReadinessAssessment/checks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedElements" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ManualDecision" eSuperTypes="#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="question" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decisionOwner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dueDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocking" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//Severity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assessment" eType="#//ProductionReadinessAssessment"
        changeable="false" transient="true" eOpposite="#//ProductionReadinessAssessment/manualDecisions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedElements" upperBound="-1"
        eType="#//ModelElement"/>
  </eClassifiers>
</ecore:EPackage>
