/**
 * Engine rework loops, between stages within phases (inside engine cycles).
 */

/** @type {Record<string, import('./process-types.mjs').IterationLoop[]>} */
export const ITERATION_LOOPS = {
  cim: [
    {
      id: "cim.loop.language-refine",
      name: "Language Refinement Loop",
      fromStageId: "cim.ph3.st2.ss1",
      toStageId: "cim.ph2.st3",
      trigger: "Entity naming conflicts during structural modeling.",
      guidance: "Update glossary, then replay information taxonomy and domain structure.",
      twinPeaks: false,
    },
    {
      id: "cim.loop.twin-peaks-explore",
      name: "Twin Peaks Exploration Loop",
      fromStageId: "cim.ph3.st3",
      toStageId: "cim.ph3.st1",
      trigger: "Behavior modeling reveals missing information items or entities.",
      guidance: "Extend taxonomy and structure, then resume behavior surface.",
      twinPeaks: true,
    },
    {
      id: "cim.loop.aggregate-rework",
      name: "Aggregate Boundary Rework",
      fromStageId: "cim.ph4.st1",
      toStageId: "cim.ph3.st3.ss1",
      trigger: "Aggregate grouping exposes command/event ownership conflicts.",
      guidance: "Adjust commands and events, then re-synthesize aggregates.",
      twinPeaks: false,
    },
    {
      id: "cim.loop.process-gap",
      name: "Process Orchestration Gap",
      fromStageId: "cim.ph4.st2.ss1",
      toStageId: "cim.ph3.st3",
      trigger: "Process steps reference behavior not on the CQRS surface.",
      guidance: "Add behavior elements, then rebuild process flows.",
      twinPeaks: false,
    },
    {
      id: "cim.loop.context-resynth",
      name: "Bounded Context Re-synthesis",
      fromStageId: "cim.ph4.st3",
      toStageId: "cim.ph4.st1",
      trigger: "Context membership is incoherent across aggregates.",
      guidance: "Revisit aggregates, then re-run context synthesis.",
      twinPeaks: false,
    },
    {
      id: "cim.loop.requirements-backfill",
      name: "Requirements Twin Peaks Loop",
      fromStageId: "cim.ph5.st1",
      toStageId: "cim.ph3.st2",
      trigger: "Requirements cannot be traced to domain or behavior elements.",
      guidance: "Extend domain model, then re-link requirements.",
      twinPeaks: true,
    },
    {
      id: "cim.loop.readiness-rework",
      name: "Readiness Rework Loop",
      fromStageId: "cim.ph5.st3",
      toStageId: "cim.ph5.st1",
      trigger: "EVL or readiness findings identify blocking gaps.",
      guidance: "Resolve at source stage; replay forward to readiness gate.",
      twinPeaks: false,
    },
  ],
  pim: [
    {
      id: "pim.loop.contract-gap",
      name: "Contract Gap Loop",
      fromStageId: "pim.ph3.st1",
      toStageId: "pim.ph2.st1",
      trigger: "Function contracts reference undefined schemas or event types.",
      guidance: "Complete contracts, then update function bindings.",
      twinPeaks: false,
    },
    {
      id: "pim.loop.data-access",
      name: "Data Access Rework",
      fromStageId: "pim.ph3.st1",
      toStageId: "pim.ph2.st2",
      trigger: "Functions need stores or access patterns not yet modeled.",
      guidance: "Extend data architecture, then replay compute tasks.",
      twinPeaks: false,
    },
    {
      id: "pim.loop.api-contract",
      name: "API Contract Loop",
      fromStageId: "pim.ph3.st2",
      toStageId: "pim.ph2.st1",
      trigger: "API routes need schemas or error mappings not defined.",
      guidance: "Complete contracts, then remap API routes.",
      twinPeaks: false,
    },
    {
      id: "pim.loop.integration-topology",
      name: "Integration Topology Loop",
      fromStageId: "pim.ph4.st1",
      toStageId: "pim.ph3.st1",
      trigger: "Channels reference producers/consumers not defined as functions.",
      guidance: "Add compute targets, then rewire integration topology.",
      twinPeaks: false,
    },
    {
      id: "pim.loop.security-gap",
      name: "Security Coverage Loop",
      fromStageId: "pim.ph5.st1",
      toStageId: "pim.ph3.st2",
      trigger: "Public endpoints lack principals or auth policies.",
      guidance: "Identify unprotected resources; add security bindings.",
      twinPeaks: false,
    },
    {
      id: "pim.loop.policy-ripple",
      name: "Policy Ripple Loop",
      fromStageId: "pim.ph5.st2",
      toStageId: "pim.ph4.st1",
      trigger: "Policies require integration or compute changes.",
      guidance: "Apply policy targets on integration/compute elements.",
      twinPeaks: false,
    },
    {
      id: "pim.loop.readiness-rework",
      name: "PIM Readiness Rework",
      fromStageId: "pim.ph6.st2",
      toStageId: "pim.ph5.st1",
      trigger: "PIM EVL or platform mapping reveals blocking gaps.",
      guidance: "Jump to earliest affected assurance stage; replay to readiness.",
      twinPeaks: false,
    },
  ],
  psm: [
    {
      id: "psm.loop.iam-baseline",
      name: "IAM Baseline Rework",
      fromStageId: "psm.ph2.st1",
      toStageId: "psm.ph1.st3",
      trigger: "Networking requires new IAM roles, KMS keys, or secrets.",
      guidance: "Extend security baseline, then replay networking.",
      twinPeaks: false,
    },
    {
      id: "psm.loop.storage-compute",
      name: "Storage–Compute Wiring Loop",
      fromStageId: "psm.ph4.st2",
      toStageId: "psm.ph3.st1",
      trigger: "Lambda mappings reference unprovisioned tables or buckets.",
      guidance: "Provision storage, then rewire compute event sources.",
      twinPeaks: false,
    },
    {
      id: "psm.loop.event-fabric",
      name: "Event Fabric Loop",
      fromStageId: "psm.ph4.st2",
      toStageId: "psm.ph4.st1",
      trigger: "Functions need EventBridge rules not yet modeled.",
      guidance: "Extend event fabric, then update Lambda targets.",
      twinPeaks: false,
    },
    {
      id: "psm.loop.api-integration",
      name: "API Integration Loop",
      fromStageId: "psm.ph5.st1",
      toStageId: "psm.ph4.st2",
      trigger: "API integrations reference incomplete Lambda or authorizers.",
      guidance: "Complete compute/identity, then rebuild API integrations.",
      twinPeaks: false,
    },
    {
      id: "psm.loop.workflow-obs",
      name: "Workflow Observability Loop",
      fromStageId: "psm.ph5.st2",
      toStageId: "psm.ph4.st2",
      trigger: "Step Functions targets changed after compute phase.",
      guidance: "Reconcile compute targets, then regenerate ASL and observability.",
      twinPeaks: false,
    },
    {
      id: "psm.loop.readiness-rework",
      name: "PSM Readiness Rework",
      fromStageId: "psm.ph6.st2",
      toStageId: "psm.ph3.st1",
      trigger: "Integration views or PSM EVL reveal broken wiring.",
      guidance: "Repair at source resource stage; regenerate views before M2T.",
      twinPeaks: false,
    },
  ],
};

export const END_TO_END_LOOPS = [
  {
    id: "e2e.loop.pim-feedback-cim",
    name: "PIM Discovery Feedback to CIM",
    fromStageId: "e2e.p3.pim-refinement",
    toStageId: "e2e.p1.cim-modeling",
    trigger: "PIM refinement reveals missing CIM concepts for the increment.",
    guidance: "Extend CIM via change workflow; re-run CIM EVL before re-transform.",
    crossLevel: true,
  },
  {
    id: "e2e.loop.psm-feedback-pim",
    name: "PSM Platform Feedback to PIM",
    fromStageId: "e2e.p5.psm-refinement",
    toStageId: "e2e.p3.pim-refinement",
    trigger: "AWS constraints require PIM architecture changes.",
    guidance: "Adjust PIM policies or integration; re-run PIM→PSM ETL.",
    crossLevel: true,
  },
  {
    id: "e2e.loop.artifact-feedback-psm",
    name: "M2T Artifact Feedback to PSM",
    fromStageId: "e2e.p7.artifact-completion",
    toStageId: "e2e.p5.psm-refinement",
    trigger: "Generated artifacts fail validation or deployment dry-run.",
    guidance: "Fix PSM at source stage; regenerate artifacts.",
    crossLevel: true,
  },
];
