/**
 * PSM modeling process, SPEM hierarchy: Phase → Stage → (subStage) → atomic Task.
 * Concept types on tasks map to AWS PSM metamodel EClasses/enums (psm-aws-combined.ecore).
 */

/** @type {import('./process-types.mjs').ProcessPhaseSpec[]} */
export const PSM_PROCESS_PHASES = [
  {
    id: "psm.ph1",
    name: "Deployment & Slice Framing",
    order: 1,
    objective:
      "Frame the current deployable slice and establish or refresh AWS account, stack, and security foundations.",
    primaryRole: "cloud-platform-engineer",
    entryCriteria: ["PIM transform complete, prior PSM increment selected, or greenfield PSM"],
    exitCriteria: [
      "AWS root and stage strategy configured",
      "Deployable-slice objective and deployment definition of done are agreed",
      "Security baseline applied",
    ],
    inEngine: true,
    stages: [
      {
        id: "psm.ph1.st0",
        name: "Deployable Slice Planning",
        objective: "Select the AWS deployable slice and define deployment review expectations.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "stack",
        tasks: [
          {
            id: "psm.ph1.st0.t1",
            name: "Plan deployable slice",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "stack",
            artifactIds: ["psm-artifact.increment-plan"],
            types: [],
            steps: [
              "Select one PIM service slice or deployment unit to materialize on AWS.",
              "Record AWS account, region, stage, networking, IAM, and deployment assumptions.",
              "Define the PSM EVL gate, artifact-generation readiness criteria, and review participants.",
            ],
            entryCriteria: [
              "PIM transform complete, prior PSM increment selected, or greenfield PSM",
            ],
            exitCriteria: ["Deployable-slice scope and definition of done are agreed"],
            validationRules: [],
            durationEstimate: "30m",
          },
        ],
      },
      {
        id: "psm.ph1.st1",
        name: "Account & Stage Strategy",
        objective:
          "Create or refresh AwsPsmModel root with partition, region, naming, and tagging policies.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "dashboard",
        tasks: [
          {
            id: "psm.ph1.st1.t1",
            name: "Create AWS PSM model root",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "dashboard",
            artifactIds: ["psm-artifact.deployment-strategy"],
            types: ["AwsPsmModel", "AwsPartition"],
            steps: [
              "Create or verify AwsPsmModel with partition and region defaults.",
              "Link to PIM source model and set lifecycle metadata.",
            ],
            entryCriteria: ["Deployable-slice scope agreed"],
            exitCriteria: ["AwsPsmModel root exists"],
            validationRules: [],
            durationEstimate: "20m",
          },
          {
            id: "psm.ph1.st1.t2",
            name: "Define stage and naming policies",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "dashboard",
            artifactIds: ["psm-artifact.deployment-strategy"],
            types: ["AwsStage", "AwsNamingPolicy", "AwsTaggingPolicy", "AwsEnvironmentClass"],
            steps: [
              "Configure AwsStage elements for dev, staging, and production.",
              "Define AwsNamingPolicy and AwsTaggingPolicy conventions.",
            ],
            entryCriteria: ["AWS PSM root exists"],
            exitCriteria: ["Stage strategy and naming policies configured"],
            validationRules: [],
            durationEstimate: "30m",
          },
        ],
      },
      {
        id: "psm.ph1.st2",
        name: "Stack Scaffolding",
        objective: "Create SAM stack with globals and CloudFormation parameters.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "stack",
        tasks: [
          {
            id: "psm.ph1.st2.t1",
            name: "Create SAM stack and globals",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "stack",
            artifactIds: ["psm-artifact.stack-scaffold"],
            types: ["SamStack", "SamGlobals"],
            steps: [
              "Create SamStack elements per deployment unit.",
              "Configure SamGlobals for shared function and API defaults.",
            ],
            entryCriteria: ["Stage strategy set"],
            exitCriteria: ["Stack scaffolding ready for resources"],
            validationRules: [],
            durationEstimate: "45m",
          },
          {
            id: "psm.ph1.st2.t2",
            name: "Define CFN parameters and outputs",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "stack",
            artifactIds: ["psm-artifact.stack-scaffold"],
            types: [
              "CfnParameter",
              "CfnMapping",
              "CfnCondition",
              "CfnOutput",
              "CloudFormationDeletionPolicy",
              "CloudFormationUpdateReplacePolicy",
            ],
            steps: [
              "Define CfnParameter, CfnMapping, and CfnCondition elements.",
              "Configure CfnOutput and resource lifecycle policies.",
            ],
            entryCriteria: ["SAM stack created"],
            exitCriteria: ["CFN scaffolding complete per stack"],
            validationRules: [],
            durationEstimate: "30m",
          },
        ],
      },
      {
        id: "psm.ph1.st3",
        name: "Security Baseline",
        objective: "Establish IAM roles, KMS keys, secrets, and SSM parameters.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "security",
        tasks: [
          {
            id: "psm.ph1.st3.t1",
            name: "Configure IAM roles and policies",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "security",
            artifactIds: ["psm-artifact.security-baseline"],
            types: [
              "AwsSecurityBaseline",
              "IamRole",
              "IamInlinePolicy",
              "IamPolicy",
              "IamManagedPolicy",
              "IamPolicyDocument",
              "IamStatement",
              "IamPrincipal",
              "IamCondition",
            ],
            steps: [
              "Establish AwsSecurityBaseline with least-privilege defaults.",
              "Create IamRole elements with inline and managed policies.",
            ],
            entryCriteria: ["Stack scaffolding complete"],
            exitCriteria: ["IAM roles cover function and service principals"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "psm.ph1.st3.t2",
            name: "Provision KMS, secrets, and SSM",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "security",
            artifactIds: ["psm-artifact.security-baseline"],
            types: [
              "KmsKey",
              "KmsAlias",
              "SecretsManagerSecret",
              "GenerateSecretStringConfig",
              "SecretRotationRules",
              "SecretRotationSchedule",
              "SecretsManagerResourcePolicy",
              "SsmParameter",
              "SsmParameterValueExpression",
              "SecretValueExpression",
            ],
            steps: [
              "Configure KmsKey and KmsAlias for encryption at rest.",
              "Create SecretsManagerSecret with rotation rules.",
              "Define SsmParameter elements for non-secret configuration.",
            ],
            entryCriteria: ["IAM roles configured"],
            exitCriteria: ["Security baseline applied"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
    ],
  },
  {
    id: "psm.ph2",
    name: "Network & Identity",
    order: 2,
    objective: "Configure VPC networking and Cognito identity resources aligned to PIM auth model.",
    primaryRole: "cloud-platform-engineer",
    entryCriteria: ["Deployment & Slice Framing complete"],
    exitCriteria: [
      "Network posture defined for workloads",
      "Identity resources match PIM auth model",
    ],
    inEngine: true,
    stages: [
      {
        id: "psm.ph2.st1",
        name: "Networking",
        objective: "Configure VPC, subnets, endpoints, and security groups for workloads.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "networking",
        tasks: [
          {
            id: "psm.ph2.st1.t1",
            name: "Configure VPC and subnets",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "networking",
            artifactIds: ["psm-artifact.network-identity"],
            types: ["Vpc", "Subnet", "VpcAttachmentConfig"],
            steps: [
              "Create Vpc and Subnet elements when VPC-attached resources are required.",
              "Configure VpcAttachmentConfig for cross-stack references.",
            ],
            entryCriteria: ["Security baseline applied"],
            exitCriteria: ["VPC topology defined for increment slice"],
            validationRules: [],
            durationEstimate: "1h",
          },
          {
            id: "psm.ph2.st1.t2",
            name: "Define endpoints and security groups",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "networking",
            artifactIds: ["psm-artifact.network-identity"],
            types: ["VpcEndpoint", "VpcEndpointReference", "SecurityGroup", "SecurityGroupRule"],
            steps: [
              "Configure VpcEndpoint elements for AWS service access.",
              "Define SecurityGroup and SecurityGroupRule for workload isolation.",
            ],
            entryCriteria: ["VPC topology defined"],
            exitCriteria: ["Network posture defined for workloads"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
      {
        id: "psm.ph2.st2",
        name: "Identity",
        objective: "Configure Cognito user pools, clients, and identity pools.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "identity",
        tasks: [
          {
            id: "psm.ph2.st2.t1",
            name: "Configure Cognito user pools",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "identity",
            artifactIds: ["psm-artifact.network-identity"],
            types: [
              "CognitoUserPool",
              "CognitoPasswordPolicy",
              "CognitoSchemaAttribute",
              "CognitoEmailConfiguration",
              "CognitoAccountRecoverySetting",
              "CognitoRecoveryMechanism",
              "CognitoLambdaConfig",
            ],
            steps: [
              "Create CognitoUserPool elements from PIM identity providers.",
              "Configure password policy, schema attributes, and recovery settings.",
            ],
            entryCriteria: ["Networking configured"],
            exitCriteria: ["User pools match PIM principal model"],
            validationRules: [],
            durationEstimate: "1h",
          },
          {
            id: "psm.ph2.st2.t2",
            name: "Configure clients, groups, and identity pools",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "identity",
            artifactIds: ["psm-artifact.network-identity"],
            types: [
              "CognitoUserPoolClient",
              "CognitoOAuthConfiguration",
              "CognitoUserPoolGroup",
              "CognitoUserPoolDomain",
              "CognitoIdentityPool",
            ],
            steps: [
              "Define CognitoUserPoolClient with OAuth configuration.",
              "Create CognitoUserPoolGroup and CognitoIdentityPool for federated access.",
            ],
            entryCriteria: ["User pools configured"],
            exitCriteria: ["Identity resources match PIM auth model"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
  {
    id: "psm.ph3",
    name: "Storage & Messaging",
    order: 3,
    objective:
      "Provision durable storage and messaging resources matching PIM data and event channels.",
    primaryRole: "cloud-platform-engineer",
    entryCriteria: ["Network & Identity complete"],
    exitCriteria: ["Durable stores match PIM data model", "Messaging matches PIM event channels"],
    inEngine: true,
    stages: [
      {
        id: "psm.ph3.st1",
        name: "Durable Storage",
        objective: "Provision DynamoDB tables and S3 buckets aligned to PIM data architecture.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "storage",
        tasks: [
          {
            id: "psm.ph3.st1.t1",
            name: "Provision DynamoDB tables",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "storage",
            artifactIds: ["psm-artifact.storage-layer"],
            types: [
              "DynamoDbTable",
              "DynamoDbAttributeDefinition",
              "DynamoDbKeySchemaElement",
              "DynamoDbProjection",
              "DynamoDbProvisionedThroughput",
              "DynamoDbOnDemandThroughput",
              "DynamoDbLocalSecondaryIndex",
              "DynamoDbGlobalSecondaryIndex",
              "DynamoDbReplicaSpecification",
              "DynamoDbStreamSpecification",
              "DynamoDbTimeToLiveSpecification",
              "DynamoDbSseSpecification",
              "DynamoDbBackupPolicy",
            ],
            steps: [
              "Create DynamoDbTable elements from PIM DataStore definitions.",
              "Configure key schema, GSIs/LSIs, streams, and TTL.",
            ],
            entryCriteria: ["Identity configured"],
            exitCriteria: ["DynamoDB tables match PIM data models"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "psm.ph3.st1.t2",
            name: "Configure S3 buckets and policies",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "storage",
            artifactIds: ["psm-artifact.storage-layer"],
            types: [
              "S3Bucket",
              "S3BucketEncryption",
              "S3OwnershipControls",
              "S3OwnershipRule",
              "S3LifecycleConfiguration",
              "S3LifecycleRule",
              "S3LifecycleFilter",
              "S3TagFilter",
              "S3Transition",
              "S3PublicAccessBlockConfiguration",
              "S3NotificationConfiguration",
              "S3NotificationRule",
              "S3ReplicationConfiguration",
              "S3ReplicationRule",
              "S3ReplicationDestination",
              "S3BucketPolicy",
              "S3NotificationDestination",
            ],
            steps: [
              "Create S3Bucket elements from PIM ObjectStore definitions.",
              "Configure encryption, lifecycle, notifications, and bucket policies.",
            ],
            entryCriteria: ["DynamoDB tables provisioned"],
            exitCriteria: ["S3 buckets match PIM object stores"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
        ],
      },
      {
        id: "psm.ph3.st2",
        name: "Messaging",
        objective: "Create SQS queues and SNS topics aligned to PIM event channels.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "messaging",
        tasks: [
          {
            id: "psm.ph3.st2.t1",
            name: "Create SQS queues",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "messaging",
            artifactIds: ["psm-artifact.messaging-layer"],
            types: ["SqsQueue", "SqsRedrivePolicy", "SqsRedriveAllowPolicy", "SqsQueuePolicy"],
            steps: [
              "Create SqsQueue elements from PIM Queue definitions.",
              "Configure redrive policies and queue policies.",
            ],
            entryCriteria: ["Durable storage provisioned"],
            exitCriteria: ["SQS queues match PIM integration topology"],
            validationRules: [],
            durationEstimate: "45m",
          },
          {
            id: "psm.ph3.st2.t2",
            name: "Configure SNS topics and subscriptions",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "messaging",
            artifactIds: ["psm-artifact.messaging-layer"],
            types: ["SnsTopic", "SnsSubscription", "SnsFilterRule", "SnsTopicPolicy"],
            steps: [
              "Create SnsTopic elements from PIM Topic definitions.",
              "Define SnsSubscription with filter rules and topic policies.",
            ],
            entryCriteria: ["SQS queues created"],
            exitCriteria: ["Messaging matches PIM event channels"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
  {
    id: "psm.ph4",
    name: "Event Fabric & Compute",
    order: 4,
    objective: "Configure EventBridge fabric and deploy Lambda compute matching PIM functions.",
    primaryRole: "cloud-platform-engineer",
    entryCriteria: ["Storage & Messaging complete for slice"],
    exitCriteria: ["Event fabric matches PIM integration", "Compute matches PIM functions"],
    inEngine: true,
    stages: [
      {
        id: "psm.ph4.st1",
        name: "Event Fabric",
        objective: "Configure EventBridge buses, rules, schedules, pipes, and API destinations.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "events",
        tasks: [
          {
            id: "psm.ph4.st1.t1",
            name: "Configure EventBridge buses and rules",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "events",
            artifactIds: ["psm-artifact.event-fabric"],
            types: [
              "EventBridgeBus",
              "EventBridgeBusPolicy",
              "EventBridgeRule",
              "EventPattern",
              "EventBridgeTarget",
              "EventBridgeTargetParameters",
              "EventBridgeSqsTargetParameters",
              "EventBridgeHttpTargetParameters",
              "HttpParameter",
              "EventBridgeBatchTargetParameters",
              "EventBridgeInputTransformer",
              "EventBridgeArchive",
              "AwsRetryPolicy",
            ],
            steps: [
              "Create EventBridgeBus and EventBridgeRule elements from PIM EventBus.",
              "Configure targets, input transformers, and retry policies.",
            ],
            entryCriteria: ["Messaging configured"],
            exitCriteria: ["EventBridge rules match PIM routing rules"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "psm.ph4.st1.t2",
            name: "Configure schedules, pipes, and connections",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "events",
            artifactIds: ["psm-artifact.event-fabric"],
            types: [
              "EventBridgeSchedule",
              "EventBridgeFlexibleTimeWindow",
              "EventBridgePipe",
              "EventBridgeAuthParameters",
              "EventBridgeApiKeyAuthParameters",
              "EventBridgeBasicAuthParameters",
              "EventBridgeOAuthParameters",
              "EventBridgeHttpParameters",
              "EventBridgeConnection",
              "EventBridgeApiDestination",
            ],
            steps: [
              "Define EventBridgeSchedule elements from PIM Schedule triggers.",
              "Configure EventBridgePipe and API destinations for external integration.",
            ],
            entryCriteria: ["EventBridge rules configured"],
            exitCriteria: ["Event fabric matches PIM integration"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "psm.ph4.st2",
        name: "Compute",
        objective: "Deploy Lambda functions with event source mappings and permissions.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "compute",
        tasks: [
          {
            id: "psm.ph4.st2.t1",
            name: "Deploy Lambda functions",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "compute",
            artifactIds: ["psm-artifact.compute-layer"],
            types: [
              "AwsLambdaFunction",
              "LambdaCodeConfig",
              "LambdaZipCodeConfig",
              "LambdaImageCodeConfig",
              "LambdaImageConfig",
              "LambdaEnvironmentVariable",
              "LambdaInvocationBinding",
              "SamFunctionEvent",
              "LambdaLayerVersion",
              "LambdaLayerPermission",
              "LambdaVersion",
              "LambdaAlias",
              "LambdaProvisionedConcurrencyConfig",
              "LambdaFileSystemConfig",
              "CodeSigningConfig",
              "PackageType",
              "LambdaArchitecture",
              "LambdaRuntimeManagementMode",
              "LambdaSnapStartApplyOn",
            ],
            steps: [
              "Create AwsLambdaFunction elements from PIM Function definitions.",
              "Configure code config, layers, aliases, and environment variables.",
            ],
            entryCriteria: ["Event fabric configured"],
            exitCriteria: ["Lambda functions match PIM compute catalog"],
            validationRules: [],
            durationEstimate: "2-3h",
          },
          {
            id: "psm.ph4.st2.t2",
            name: "Configure event sources and permissions",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "compute",
            artifactIds: ["psm-artifact.compute-layer"],
            types: [
              "LambdaEventSourceMapping",
              "SqsLambdaEventSourceMapping",
              "DynamoDbStreamLambdaEventSourceMapping",
              "GenericLambdaEventSourceMapping",
              "LambdaDeadLetterConfig",
              "LambdaEventInvokeConfig",
              "LambdaDestinationConfig",
              "LambdaTracingConfig",
              "LambdaLoggingConfig",
              "LambdaPermission",
              "LambdaFunctionUrl",
              "LambdaUrlCorsConfiguration",
              "LambdaTracingMode",
              "LambdaInvokeMode",
              "LambdaFunctionUrlAuthType",
              "LambdaRecursiveLoopMode",
              "LambdaEventSourceKind",
              "StartingPosition",
            ],
            steps: [
              "Configure LambdaEventSourceMapping for SQS, DynamoDB streams, and EventBridge.",
              "Set LambdaPermission, dead-letter config, and tracing/logging.",
            ],
            entryCriteria: ["Lambda functions deployed"],
            exitCriteria: ["Compute matches PIM functions"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
        ],
      },
    ],
  },
  {
    id: "psm.ph5",
    name: "API & Orchestration",
    order: 5,
    objective: "Configure API Gateway exposure and Step Functions workflows with observability.",
    primaryRole: "cloud-platform-engineer",
    entryCriteria: ["Event Fabric & Compute complete for slice"],
    exitCriteria: ["API Gateway matches PIM APIs", "Workflows and observability complete"],
    inEngine: true,
    stages: [
      {
        id: "psm.ph5.st1",
        name: "API Gateway",
        objective: "Configure HTTP/REST/WebSocket APIs with routes, integrations, and authorizers.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "api",
        tasks: [
          {
            id: "psm.ph5.st1.t1",
            name: "Configure APIs and routes",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "api",
            artifactIds: ["psm-artifact.api-layer"],
            types: [
              "ApiGatewayApi",
              "HttpApi",
              "RestApi",
              "WebSocketApi",
              "ApiGatewayRoute",
              "HttpApiRoute",
              "RestApiRoute",
              "RestApiResource",
              "RestApiMethod",
              "WebSocketRoute",
              "ApiGatewayKind",
              "ApiGatewayEndpointType",
              "ApiGatewayHttpMethod",
            ],
            steps: [
              "Create HttpApi, RestApi, and WebSocketApi from PIM Api definitions.",
              "Define routes, resources, and methods per API style.",
            ],
            entryCriteria: ["Compute deployed"],
            exitCriteria: ["API routes match PIM API catalog"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "psm.ph5.st1.t2",
            name: "Configure integrations and authorizers",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "api",
            artifactIds: ["psm-artifact.api-layer"],
            types: [
              "ApiGatewayRequestModel",
              "ApiGatewayResponseModel",
              "ApiGatewayRequestValidator",
              "ApiGatewayRouteSetting",
              "ApiGatewayAccessLogSetting",
              "ApiGatewayIntegration",
              "ApiGatewayIntegrationRequestTemplate",
              "ApiGatewayIntegrationResponseParameter",
              "ApiGatewayStage",
              "HttpApiStage",
              "RestApiStage",
              "WebSocketStage",
              "ApiGatewayAuthorizer",
              "JwtAuthorizer",
              "CognitoAuthorizer",
              "LambdaAuthorizer",
              "ApiGatewayDomainName",
              "ApiGatewayBasePathMapping",
              "ApiGatewayApiKey",
              "ApiGatewayUsagePlan",
              "ApiGatewayUsagePlanKey",
              "ApiGatewayDeployment",
              "ApiGatewayTracingConfig",
              "WafWebAclAssociation",
              "ApiGatewayAuthorizationType",
              "ApiGatewayIntegrationType",
            ],
            steps: [
              "Configure ApiGatewayIntegration to Lambda functions.",
              "Set up authorizers, stages, and WAF associations.",
            ],
            entryCriteria: ["API routes defined"],
            exitCriteria: ["API Gateway matches PIM APIs"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
        ],
      },
      {
        id: "psm.ph5.st2",
        name: "Workflow & Observability",
        objective: "Deploy Step Functions state machines and CloudWatch observability stack.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "workflow",
        subStages: [
          {
            id: "psm.ph5.st2.ss1",
            name: "Step Functions",
            objective: "Deploy state machines with ASL from PIM workflows.",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "workflow",
            tasks: [
              {
                id: "psm.ph5.st2.ss1.t1",
                name: "Deploy state machines",
                primaryRole: "cloud-platform-engineer",
                viewpoint: "workflow",
                artifactIds: ["psm-artifact.workflow-observability"],
                types: [
                  "StepFunctionStateMachine",
                  "AslDocument",
                  "AslState",
                  "AslPassState",
                  "AslTaskState",
                  "AslChoiceState",
                  "AslWaitState",
                  "AslSucceedState",
                  "AslFailState",
                  "AslParallelState",
                  "AslMapState",
                  "AslBranch",
                  "AslMapConfig",
                  "AslRetryRule",
                  "AslCatchRule",
                  "AslChoiceRule",
                  "StepFunctionLoggingConfig",
                  "StepFunctionTracingConfig",
                  "SamStateMachineEvent",
                ],
                steps: [
                  "Create StepFunctionStateMachine from PIM Workflow definitions.",
                  "Select the concrete AslPassState, AslTaskState, AslChoiceState, AslWaitState, AslSucceedState, AslFailState, AslParallelState, or AslMapState classifier for every state.",
                  "Configure ASL transitions, retry/catch rules, branches, map processors, and logging.",
                ],
                entryCriteria: ["API Gateway configured"],
                exitCriteria: ["State machines match PIM workflows"],
                validationRules: [],
                durationEstimate: "1-2h",
              },
            ],
          },
          {
            id: "psm.ph5.st2.ss2",
            name: "CloudWatch Observability",
            objective: "Configure logs, metrics, alarms, and dashboards.",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "workflow",
            tasks: [
              {
                id: "psm.ph5.st2.ss2.t1",
                name: "Configure CloudWatch logs and metrics",
                primaryRole: "cloud-platform-engineer",
                viewpoint: "workflow",
                artifactIds: ["psm-artifact.workflow-observability"],
                types: [
                  "CloudWatchLogGroup",
                  "CloudWatchMetricFilter",
                  "CloudWatchMetricTransformation",
                  "CloudWatchLogSubscriptionFilter",
                  "MetricDimension",
                ],
                steps: [
                  "Create CloudWatchLogGroup elements for functions and APIs.",
                  "Configure metric filters and subscription filters.",
                ],
                entryCriteria: ["State machines deployed"],
                exitCriteria: ["Logging and metrics configured"],
                validationRules: [],
                durationEstimate: "45m",
              },
              {
                id: "psm.ph5.st2.ss2.t2",
                name: "Configure alarms and dashboards",
                primaryRole: "cloud-platform-engineer",
                viewpoint: "workflow",
                artifactIds: ["psm-artifact.workflow-observability"],
                types: [
                  "CloudWatchAlarm",
                  "CloudWatchCompositeAlarm",
                  "CloudWatchDashboard",
                  "TracingConfig",
                  "CorsConfiguration",
                ],
                steps: [
                  "Define CloudWatchAlarm and composite alarms from PIM SLOs.",
                  "Create CloudWatchDashboard for increment slice.",
                ],
                entryCriteria: ["Logging and metrics configured"],
                exitCriteria: ["Workflows and observability complete"],
                validationRules: [],
                durationEstimate: "45m",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "psm.ph6",
    name: "Integration Views & Readiness",
    order: 6,
    objective: "Create integration relationship views, close traceability, and pass PSM EVL gate.",
    primaryRole: "process-reviewer",
    entryCriteria: ["API & Orchestration complete for slice"],
    exitCriteria: [
      "PSM EVL passes",
      "Readiness gate approved",
      "PSM increment reviewed and improvement actions captured",
    ],
    inEngine: true,
    stages: [
      {
        id: "psm.ph6.st1",
        name: "Integration Views",
        objective: "Create cross-resource relationship views for deployment wiring validation.",
        primaryRole: "cloud-platform-engineer",
        viewpoint: "readiness",
        tasks: [
          {
            id: "psm.ph6.st1.t1",
            name: "Create integration relationship views",
            primaryRole: "cloud-platform-engineer",
            viewpoint: "readiness",
            artifactIds: ["psm-artifact.integration-views"],
            types: [
              "AwsRelationshipView",
              "ApiGatewayLambdaIntegrationView",
              "EventBridgeLambdaTargetView",
              "SnsLambdaSubscriptionView",
              "SqsLambdaEventSourceView",
              "StepFunctionEventBridgeTargetView",
              "S3LambdaNotificationView",
              "S3QueueNotificationView",
              "S3TopicNotificationView",
              "AwsTag",
              "ResourceImport",
              "NativeProperty",
            ],
            steps: [
              "Generate AwsRelationshipView elements for Lambda integrations.",
              "Validate event source, API, and notification wiring views.",
              "Apply AwsTag and ResourceImport for cross-stack references.",
            ],
            entryCriteria: ["Workflow and observability complete"],
            exitCriteria: ["Integration views cover all wiring paths"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "psm.ph6.st2",
        name: "Trace & Readiness Gate",
        objective: "Close trace links and production readiness before M2T generation.",
        primaryRole: "process-reviewer",
        viewpoint: "readiness",
        tasks: [
          {
            id: "psm.ph6.st2.t1",
            name: "Complete trace and readiness",
            primaryRole: "process-reviewer",
            viewpoint: "readiness",
            artifactIds: ["psm-artifact.deployment-readiness"],
            types: [],
            readinessTypes: true,
            steps: [
              "Build TraceModel links across PIM and PSM resources.",
              "Complete ProductionReadinessAssessment and resolve findings.",
            ],
            entryCriteria: ["Integration views complete"],
            exitCriteria: ["PSM EVL passes; readiness gate approved"],
            validationRules: ["psm-semantic-validation"],
            durationEstimate: "1-2h",
          },
        ],
      },
      {
        id: "psm.ph6.st3",
        name: "Increment Review & Adapt",
        objective:
          "Review the AWS deployment slice, accept the increment, and adapt the next cycle.",
        primaryRole: "process-reviewer",
        viewpoint: "readiness",
        tasks: [
          {
            id: "psm.ph6.st3.t1",
            name: "Review and adapt PSM increment",
            primaryRole: "process-reviewer",
            viewpoint: "readiness",
            artifactIds: ["psm-artifact.increment-review"],
            types: [],
            steps: [
              "Review AWS resource wiring, least-privilege posture, and artifact-generation readiness.",
              "Record accepted scope, deferred deployment decisions, and operational feedback.",
              "Create improvement actions and backlog adjustments for the next deployable slice.",
            ],
            entryCriteria: ["PSM EVL passes or all blocking findings are dispositioned"],
            exitCriteria: [
              "Increment accepted or rework loop selected; improvement actions captured",
            ],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
];
