/**
 * CIM modeling process — SPEM hierarchy: Phase → Stage → (subStage) → atomic Task.
 * Concept types on tasks map to CIM metamodel EClasses/enums (cim-combined.ecore).
 */

/** @type {import('./process-types.mjs').ProcessPhaseSpec[]} */
export const CIM_PROCESS_PHASES = [
  {
    id: "cim.ph1",
    name: "Establishment",
    order: 1,
    objective: "Establish the CIM program container and strategic intent that anchors all later modeling.",
    primaryRole: "business-modeler",
    entryCriteria: ["Modless project created"],
    exitCriteria: ["CIMModel root exists", "At least one BusinessGoal with KPI"],
    inEngine: false,
    stages: [
      {
        id: "cim.ph1.st1",
        name: "Program Charter",
        objective: "Create the CIMModel root and modeling conventions.",
        primaryRole: "business-modeler",
        viewpoint: "dashboard",
        tasks: [
          {
            id: "cim.ph1.st1.t1",
            name: "Create CIM model root",
            primaryRole: "business-modeler",
            viewpoint: "dashboard",
            artifactIds: ["cim-artifact.model-root"],
            types: ["CIMModel"],
            steps: [
              "Create CIMModel with domainName and businessScope.",
              "Set organizationName, modelingDate, and language.",
              "Apply lifecycle status and annotation conventions on the root.",
            ],
            entryCriteria: ["Project created"],
            exitCriteria: ["CIMModel root with domainName exists"],
            validationRules: [],
            durationEstimate: "20m",
          },
        ],
      },
      {
        id: "cim.ph1.st2",
        name: "Strategic Framing",
        objective: "Capture measurable business intent using GQM before domain modeling.",
        primaryRole: "business-modeler",
        viewpoint: "requirements",
        tasks: [
          {
            id: "cim.ph1.st2.t1",
            name: "Define business goals and KPIs",
            primaryRole: "business-modeler",
            viewpoint: "requirements",
            artifactIds: ["cim-artifact.strategic-intent"],
            types: ["BusinessGoal", "KPI", "Priority"],
            steps: [
              "Capture BusinessGoal elements with success criteria.",
              "Define measurable KPIs linked to each goal.",
            ],
            entryCriteria: ["CIM model root exists"],
            exitCriteria: ["At least one goal with linked KPI"],
            validationRules: ["CIM-GOAL-001", "CIM-KPI-001"],
            durationEstimate: "45m",
          },
          {
            id: "cim.ph1.st2.t2",
            name: "Identify stakeholders",
            primaryRole: "business-modeler",
            viewpoint: "requirements",
            artifactIds: ["cim-artifact.strategic-intent"],
            types: ["Stakeholder"],
            steps: ["Register stakeholders and their concerns linked to goals."],
            entryCriteria: ["Goals drafted"],
            exitCriteria: ["Stakeholders identified for primary outcomes"],
            validationRules: [],
            durationEstimate: "30m",
          },
        ],
      },
    ],
  },
  {
    id: "cim.ph2",
    name: "Context Discovery",
    order: 2,
    objective: "Map who participates in the domain, what the organization can do, and shared vocabulary.",
    primaryRole: "business-modeler",
    entryCriteria: ["Phase Establishment complete"],
    exitCriteria: ["Actors, capabilities, and glossary cover the increment slice"],
    inEngine: true,
    stages: [
      {
        id: "cim.ph2.st1",
        name: "Participation Model",
        objective: "Model human/system actors, roles, and boundary external systems.",
        primaryRole: "business-modeler",
        viewpoint: "actor",
        tasks: [
          {
            id: "cim.ph2.st1.t1",
            name: "Model actors and roles",
            primaryRole: "business-modeler",
            viewpoint: "actor",
            artifactIds: ["cim-artifact.participation-model"],
            types: ["Actor", "Role", "ActorType", "TrustLevel"],
            steps: [
              "Model human and system Actor elements with trust levels.",
              "Define Role elements and link to actors.",
            ],
            entryCriteria: ["Strategic intent captured"],
            exitCriteria: ["Actors exist for primary user journeys"],
            validationRules: [],
            durationEstimate: "45m",
          },
          {
            id: "cim.ph2.st1.t2",
            name: "Register external systems",
            primaryRole: "business-modeler",
            viewpoint: "actor",
            artifactIds: ["cim-artifact.participation-model"],
            types: ["ExternalSystem"],
            steps: ["Register ExternalSystem actors at domain boundaries."],
            entryCriteria: ["Actors modeled"],
            exitCriteria: ["External integrations at boundaries identified"],
            validationRules: [],
            durationEstimate: "20m",
          },
        ],
      },
      {
        id: "cim.ph2.st2",
        name: "Capability Topology",
        objective: "Map business capabilities to goals and record dependencies.",
        primaryRole: "business-modeler",
        viewpoint: "capability",
        tasks: [
          {
            id: "cim.ph2.st2.t1",
            name: "Map business capabilities",
            primaryRole: "business-modeler",
            viewpoint: "capability",
            artifactIds: ["cim-artifact.capability-map"],
            types: ["BusinessCapability", "CapabilityCriticality"],
            steps: [
              "Create BusinessCapability elements linked to goals.",
              "Set criticality for each capability in the increment slice.",
            ],
            entryCriteria: ["Participation model drafted"],
            exitCriteria: ["Capabilities cover core value streams for slice"],
            validationRules: [],
            durationEstimate: "1h",
          },
          {
            id: "cim.ph2.st2.t2",
            name: "Record capability dependencies",
            primaryRole: "business-modeler",
            viewpoint: "capability",
            artifactIds: ["cim-artifact.capability-map"],
            types: ["CapabilityDependency"],
            steps: ["Model CapabilityDependency relationships between capabilities."],
            entryCriteria: ["Capability map drafted"],
            exitCriteria: ["Dependencies documented for slice"],
            validationRules: [],
            durationEstimate: "30m",
          },
        ],
      },
      {
        id: "cim.ph2.st3",
        name: "Ubiquitous Language",
        objective: "Build shared glossary before structural modeling (DDD).",
        primaryRole: "business-modeler",
        viewpoint: "capability",
        tasks: [
          {
            id: "cim.ph2.st3.t1",
            name: "Define domain glossary",
            primaryRole: "business-modeler",
            viewpoint: "capability",
            artifactIds: ["cim-artifact.glossary"],
            types: ["UbiquitousLanguageTerm"],
            steps: [
              "Define UbiquitousLanguageTerm entries with definitions and examples.",
              "Link terms to capabilities where helpful.",
              "Resolve naming conflicts before entity modeling.",
            ],
            entryCriteria: ["Capability map drafted"],
            exitCriteria: ["Glossary covers core domain nouns for slice"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
  {
    id: "cim.ph3",
    name: "Domain Exploration",
    order: 3,
    objective: "Explore information, structure, and behavior using Twin Peaks — iterate until CQRS surface is coherent.",
    primaryRole: "business-modeler",
    entryCriteria: ["Context Discovery complete for slice"],
    exitCriteria: ["Commands, queries, and events cover primary use cases"],
    inEngine: true,
    stages: [
      {
        id: "cim.ph3.st1",
        name: "Information Architecture",
        objective: "Classify data and name information items before entities (CIM-ENTITY-001).",
        primaryRole: "business-modeler",
        viewpoint: "domain",
        subStages: [
          {
            id: "cim.ph3.st1.ss1",
            name: "Data Classification",
            objective: "Define confidentiality and handling classifications.",
            primaryRole: "business-modeler",
            viewpoint: "domain",
            tasks: [
              {
                id: "cim.ph3.st1.ss1.t1",
                name: "Define data classifications",
                primaryRole: "business-modeler",
                viewpoint: "domain",
                artifactIds: ["cim-artifact.information-taxonomy"],
                types: ["DataClassification", "DataKind", "QualityType", "LegalBasis"],
                steps: ["Create DataClassification elements with confidentiality levels."],
                entryCriteria: ["Glossary established"],
                exitCriteria: ["Classifications cover sensitive categories"],
                validationRules: [],
                durationEstimate: "30m",
              },
            ],
          },
          {
            id: "cim.ph3.st1.ss2",
            name: "Information Items",
            objective: "Name and type the facts the domain cares about.",
            primaryRole: "business-modeler",
            viewpoint: "domain",
            tasks: [
              {
                id: "cim.ph3.st1.ss2.t1",
                name: "Create information items",
                primaryRole: "business-modeler",
                viewpoint: "domain",
                artifactIds: ["cim-artifact.information-taxonomy"],
                types: [
                  "InformationItem",
                  "Identifiability",
                  "PrimitiveBusinessType",
                  "IdentityStrategy",
                ],
                steps: [
                  "Create InformationItem elements for each planned entity attribute group.",
                  "Set identifiability and data kind on each item.",
                ],
                entryCriteria: ["Classifications defined"],
                exitCriteria: ["Information items exist for planned entities"],
                validationRules: ["CIM-ENTITY-001"],
                durationEstimate: "1h",
              },
            ],
          },
        ],
      },
      {
        id: "cim.ph3.st2",
        name: "Structural Domain Model",
        objective: "Model entities, value objects, relationships, lifecycle, and invariants.",
        primaryRole: "business-modeler",
        viewpoint: "domain",
        subStages: [
          {
            id: "cim.ph3.st2.ss1",
            name: "Entities & Lifecycle",
            objective: "Model stateful domain entities with identity from information items.",
            primaryRole: "business-modeler",
            viewpoint: "domain",
            tasks: [
              {
                id: "cim.ph3.st2.ss1.t1",
                name: "Model domain entities",
                primaryRole: "business-modeler",
                viewpoint: "domain",
                artifactIds: ["cim-artifact.domain-structure"],
                types: ["DomainEntity", "LifecycleStateDefinition", "BusinessInvariant"],
                steps: [
                  "Create DomainEntity elements referencing primary InformationItem identity.",
                  "Define lifecycle states and business invariants per entity.",
                ],
                entryCriteria: ["Information taxonomy complete"],
                exitCriteria: ["Core entities for slice modeled"],
                validationRules: ["CIM-ENTITY-001"],
                durationEstimate: "1-2h",
              },
            ],
          },
          {
            id: "cim.ph3.st2.ss2",
            name: "Value Objects & Relationships",
            objective: "Model descriptive types and associations between domain concepts.",
            primaryRole: "business-modeler",
            viewpoint: "domain",
            tasks: [
              {
                id: "cim.ph3.st2.ss2.t1",
                name: "Model value objects and relationships",
                primaryRole: "business-modeler",
                viewpoint: "domain",
                artifactIds: ["cim-artifact.domain-structure"],
                types: ["ValueObject", "DomainRelationship", "DomainRelationshipType", "DomainConcept"],
                steps: [
                  "Add ValueObject elements for descriptive data.",
                  "Model DomainRelationship elements between concepts.",
                ],
                entryCriteria: ["Entities modeled"],
                exitCriteria: ["Relationships and VOs complete for slice"],
                validationRules: ["CIM-RELATIONSHIP-001"],
                durationEstimate: "1h",
              },
            ],
          },
        ],
      },
      {
        id: "cim.ph3.st3",
        name: "Behavior Surface",
        objective: "CQRS and event storming — commands, queries, events linked to actors and capabilities.",
        primaryRole: "business-modeler",
        viewpoint: "eventstorming",
        subStages: [
          {
            id: "cim.ph3.st3.ss1",
            name: "Commands",
            objective: "Model state-changing operations with outcomes and preconditions.",
            primaryRole: "business-modeler",
            viewpoint: "eventstorming",
            tasks: [
              {
                id: "cim.ph3.st3.ss1.t1",
                name: "Model commands and outcomes",
                primaryRole: "business-modeler",
                viewpoint: "eventstorming",
                artifactIds: ["cim-artifact.behavior-surface"],
                types: ["Command", "CommandOutcome", "CommandType"],
                steps: [
                  "Create Command elements with actors and target capabilities.",
                  "Define CommandOutcome and link expected/rejection events.",
                ],
                entryCriteria: ["Domain structure drafted"],
                exitCriteria: ["Commands cover primary write use cases"],
                validationRules: [],
                durationEstimate: "1h",
              },
            ],
          },
          {
            id: "cim.ph3.st3.ss2",
            name: "Queries",
            objective: "Model read operations with freshness needs.",
            primaryRole: "business-modeler",
            viewpoint: "eventstorming",
            tasks: [
              {
                id: "cim.ph3.st3.ss2.t1",
                name: "Model queries",
                primaryRole: "business-modeler",
                viewpoint: "eventstorming",
                artifactIds: ["cim-artifact.behavior-surface"],
                types: ["Query", "QueryType", "FreshnessNeed"],
                steps: [
                  "Create Query elements linked to actors and information items.",
                  "Set freshness requirements per query.",
                ],
                entryCriteria: ["Commands modeled"],
                exitCriteria: ["Queries cover primary read use cases"],
                validationRules: [],
                durationEstimate: "45m",
              },
            ],
          },
          {
            id: "cim.ph3.st3.ss3",
            name: "Events & Guards",
            objective: "Model domain events, business errors, and guard conditions.",
            primaryRole: "business-modeler",
            viewpoint: "eventstorming",
            tasks: [
              {
                id: "cim.ph3.st3.ss3.t1",
                name: "Model events, errors, and conditions",
                primaryRole: "business-modeler",
                viewpoint: "eventstorming",
                artifactIds: ["cim-artifact.behavior-surface"],
                types: ["BusinessEvent", "BusinessError", "Condition", "EventTimeSemantics"],
                steps: [
                  "Create BusinessEvent elements emitted by commands or external systems.",
                  "Define BusinessError and Condition elements guarding behavior.",
                ],
                entryCriteria: ["Commands and queries modeled"],
                exitCriteria: ["Event vocabulary covers slice workflows"],
                validationRules: [],
                durationEstimate: "1h",
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "cim.ph4",
    name: "Domain Synthesis",
    order: 4,
    objective: "Synthesize transactional boundaries, orchestration, and bounded contexts from explored domain.",
    primaryRole: "business-modeler",
    entryCriteria: ["Domain Exploration coherent for slice"],
    exitCriteria: ["Bounded contexts assigned with memberships"],
    inEngine: true,
    stages: [
      {
        id: "cim.ph4.st1",
        name: "Aggregate Boundaries",
        objective: "Group entities into consistency boundaries with command/event ownership.",
        primaryRole: "business-modeler",
        viewpoint: "aggregate",
        tasks: [
          {
            id: "cim.ph4.st1.t1",
            name: "Define aggregate candidates",
            primaryRole: "business-modeler",
            viewpoint: "aggregate",
            artifactIds: ["cim-artifact.aggregate-model"],
            types: ["AggregateCandidate", "ConsistencyExpectation", "InteractionExpectation"],
            steps: [
              "Create AggregateCandidate groupings with handled commands and emitted events.",
              "Document consistency and interaction expectations.",
            ],
            entryCriteria: ["Behavior surface modeled"],
            exitCriteria: ["Aggregates align with command/event ownership"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "cim.ph4.st2",
        name: "Process Orchestration",
        objective: "Model long-running business flows, policies, and decisions.",
        primaryRole: "business-modeler",
        viewpoint: "process",
        subStages: [
          {
            id: "cim.ph4.st2.ss1",
            name: "Business Processes",
            objective: "Orchestrate commands, events, and human steps into end-to-end flows.",
            primaryRole: "business-modeler",
            viewpoint: "process",
            tasks: [
              {
                id: "cim.ph4.st2.ss1.t1",
                name: "Model business processes",
                primaryRole: "business-modeler",
                viewpoint: "process",
                artifactIds: ["cim-artifact.process-model"],
                types: [
                  "BusinessProcess",
                  "ProcessStep",
                  "StartStep",
                  "EndStep",
                  "CommandStep",
                  "QueryStep",
                  "EventStep",
                  "PolicyStep",
                  "HumanTaskStep",
                  "ExternalInteractionStep",
                  "DecisionStep",
                  "WaitStep",
                  "ProcessTransition",
                  "ProcessKind",
                  "StepKind",
                  "ExceptionScenario",
                  "TemporalConstraint",
                ],
                steps: [
                  "Create BusinessProcess with step hierarchy and transitions.",
                  "Connect steps to modeled commands, queries, events, and policies.",
                ],
                entryCriteria: ["Aggregates defined"],
                exitCriteria: ["Key processes orchestrate modeled behavior"],
                validationRules: [],
                durationEstimate: "2h",
              },
            ],
          },
          {
            id: "cim.ph4.st2.ss2",
            name: "Policies & Decisions",
            objective: "Encode business rules and decision tables.",
            primaryRole: "business-modeler",
            viewpoint: "decision",
            tasks: [
              {
                id: "cim.ph4.st2.ss2.t1",
                name: "Define policies and decision tables",
                primaryRole: "business-modeler",
                viewpoint: "decision",
                artifactIds: ["cim-artifact.decision-model"],
                types: ["Policy", "DecisionTable", "DecisionRule", "PolicyType"],
                steps: [
                  "Create Policy elements guarding commands, events, and processes.",
                  "Model DecisionTable with DecisionRule rows for branching logic.",
                ],
                entryCriteria: ["Processes drafted"],
                exitCriteria: ["Policies linked to behavior elements"],
                validationRules: [],
                durationEstimate: "1h",
              },
            ],
          },
        ],
      },
      {
        id: "cim.ph4.st3",
        name: "Bounded Context Synthesis",
        objective: "Assign capabilities, domain, behavior, and policies into cohesive contexts.",
        primaryRole: "business-modeler",
        viewpoint: "capability",
        tasks: [
          {
            id: "cim.ph4.st3.t1",
            name: "Synthesize bounded contexts",
            primaryRole: "business-modeler",
            viewpoint: "capability",
            artifactIds: ["cim-artifact.context-map"],
            types: ["BoundedContextCandidate"],
            steps: [
              "Group capabilities, entities, CQRS, events, and policies into contexts.",
              "Validate memberships reference concrete modeled elements.",
            ],
            entryCriteria: ["Process and behavior complete"],
            exitCriteria: ["Contexts have non-empty memberships"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
    ],
  },
  {
    id: "cim.ph5",
    name: "Convergence & Readiness",
    order: 5,
    objective: "Backfill requirements, record transformation contracts, close traceability and EVL gate.",
    primaryRole: "requirements-engineer",
    entryCriteria: ["Domain Synthesis complete for slice"],
    exitCriteria: ["CIM EVL passes", "Readiness gate approved"],
    inEngine: true,
    stages: [
      {
        id: "cim.ph5.st1",
        name: "Requirements Engineering",
        objective: "Twin Peaks backfill — formalize requirements traced to modeled elements.",
        primaryRole: "requirements-engineer",
        viewpoint: "governance",
        tasks: [
          {
            id: "cim.ph5.st1.t1",
            name: "Formalize requirements",
            primaryRole: "requirements-engineer",
            viewpoint: "governance",
            artifactIds: ["cim-artifact.requirements-package"],
            types: [
              "Requirement",
              "RequirementRelationship",
              "AcceptanceCriterion",
              "NonFunctionalRequirement",
              "QualityScenario",
              "RequirementType",
              "RequirementSourceType",
              "RequirementRelationshipKind",
              "QualityType",
            ],
            steps: [
              "Create Requirement elements with constrains links to domain and behavior.",
              "Add AcceptanceCriterion per requirement.",
            ],
            entryCriteria: ["Bounded contexts synthesized"],
            exitCriteria: ["Requirements trace to goals and model elements"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "cim.ph5.st1.t2",
            name: "Apply governance constraints",
            primaryRole: "requirements-engineer",
            viewpoint: "governance",
            artifactIds: ["cim-artifact.governance-package"],
            types: ["SecurityConstraint", "PrivacyConstraint", "ComplianceConstraint"],
            steps: [
              "Record security, privacy, and compliance constraints on actors and information items.",
            ],
            entryCriteria: ["Requirements drafted"],
            exitCriteria: ["Governance constraints linked to targets"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "cim.ph5.st2",
        name: "Transformation Contracts",
        objective: "Document risks, assumptions, and CIM→PIM transformation profile.",
        primaryRole: "business-modeler",
        viewpoint: "traceability",
        tasks: [
          {
            id: "cim.ph5.st2.t1",
            name: "Record transformation metadata",
            primaryRole: "business-modeler",
            viewpoint: "traceability",
            artifactIds: ["cim-artifact.transformation-contract"],
            types: ["Risk", "Assumption", "Hotspot", "TransformationProfile"],
            steps: [
              "Record Risk, Assumption, and Hotspot elements on model hotspots.",
              "Define TransformationProfile for CIM→PIM with manual decisions.",
            ],
            entryCriteria: ["Governance captured"],
            exitCriteria: ["Transformation profile ready for ETL"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
      {
        id: "cim.ph5.st3",
        name: "Traceability & Readiness Gate",
        objective: "Close trace links and production readiness before CIM→PIM.",
        primaryRole: "process-reviewer",
        viewpoint: "traceability",
        tasks: [
          {
            id: "cim.ph5.st3.t1",
            name: "Complete trace and readiness",
            primaryRole: "process-reviewer",
            viewpoint: "traceability",
            artifactIds: ["cim-artifact.trace-readiness"],
            types: [],
            readinessTypes: true,
            steps: [
              "Build TraceModel links across goals, requirements, and domain.",
              "Complete ProductionReadinessAssessment and resolve findings.",
            ],
            entryCriteria: ["Transformation contracts recorded"],
            exitCriteria: ["CIM EVL passes; readiness approved"],
            validationRules: ["cim-semantic-validation"],
            durationEstimate: "1-2h",
          },
        ],
      },
    ],
  },
];
