/**
 * PIM modeling process, SPEM hierarchy: Phase → Stage → (subStage) → atomic Task.
 * Concept types on tasks map to PIM metamodel EClasses/enums (pim-combined.ecore).
 */

/** @type {import('./process-types.mjs').ProcessPhaseSpec[]} */
export const PIM_PROCESS_PHASES = [
  {
    id: "pim.ph1",
    name: "Architecture & Slice Framing",
    order: 1,
    objective:
      "Frame the current service slice, establish or refresh PIM posture, and align serverless boundaries to CIM intent.",
    primaryRole: "solution-architect",
    entryCriteria: ["CIM transform complete, prior PIM increment selected, or greenfield PIM"],
    exitCriteria: [
      "PIM root configured",
      "Service-slice objective and architecture definition of done are agreed",
      "Services cover deployable boundaries for the slice",
    ],
    inEngine: true,
    stages: [
      {
        id: "pim.ph1.st0",
        name: "Service Slice Planning",
        objective: "Select the PIM service slice and define architecture review expectations.",
        primaryRole: "solution-architect",
        viewpoint: "services",
        tasks: [
          {
            id: "pim.ph1.st0.t1",
            name: "Plan service slice",
            primaryRole: "solution-architect",
            viewpoint: "services",
            artifactIds: ["pim-artifact.increment-plan"],
            types: [],
            steps: [
              "Select one service slice traced to CIM goals, bounded contexts, and behavior.",
              "Record scope boundaries, architectural risks, manual transform decisions, and definition of done.",
              "Confirm the expected PIM EVL gate and review participants for the cycle.",
            ],
            entryCriteria: [
              "CIM transform complete, prior PIM increment selected, or greenfield PIM",
            ],
            exitCriteria: ["Service-slice scope and definition of done are agreed"],
            validationRules: [],
            durationEstimate: "30m",
          },
        ],
      },
      {
        id: "pim.ph1.st1",
        name: "Architecture Posture",
        objective:
          "Create or refresh the PIMModel root with architecture style and implementation profile.",
        primaryRole: "solution-architect",
        viewpoint: "dashboard",
        tasks: [
          {
            id: "pim.ph1.st1.t1",
            name: "Create PIM model root",
            primaryRole: "solution-architect",
            viewpoint: "dashboard",
            artifactIds: ["pim-artifact.architecture-posture"],
            types: ["PIMModel"],
            steps: [
              "Create or verify PIMModel with domain linkage to CIM source.",
              "Set modeling date, lifecycle status, and annotation conventions.",
            ],
            entryCriteria: ["Service-slice scope agreed"],
            exitCriteria: ["PIMModel root exists"],
            validationRules: [],
            durationEstimate: "20m",
          },
          {
            id: "pim.ph1.st1.t2",
            name: "Set architecture posture",
            primaryRole: "solution-architect",
            viewpoint: "dashboard",
            artifactIds: ["pim-artifact.architecture-posture"],
            types: ["ImplementationProfile", "ArchitectureStyle"],
            steps: [
              "Configure ImplementationProfile with serverless posture and platform assumptions.",
              "Select ArchitectureStyle and document key architectural decisions.",
            ],
            entryCriteria: ["PIM model root exists"],
            exitCriteria: ["Architecture style and profile configured"],
            validationRules: [],
            durationEstimate: "30m",
          },
        ],
      },
      {
        id: "pim.ph1.st2",
        name: "Service Boundaries",
        objective:
          "Define serverless services and element memberships aligned to bounded contexts.",
        primaryRole: "solution-architect",
        viewpoint: "services",
        tasks: [
          {
            id: "pim.ph1.st2.t1",
            name: "Define serverless services",
            primaryRole: "solution-architect",
            viewpoint: "services",
            artifactIds: ["pim-artifact.service-map"],
            types: ["ServerlessService", "BoundaryType"],
            steps: [
              "Create ServerlessService elements aligned to CIM bounded contexts.",
              "Set boundary type and ownership scope per service.",
            ],
            entryCriteria: ["Architecture posture set"],
            exitCriteria: ["Services defined for increment slice"],
            validationRules: [],
            durationEstimate: "1h",
          },
          {
            id: "pim.ph1.st2.t2",
            name: "Assign element memberships",
            primaryRole: "solution-architect",
            viewpoint: "services",
            artifactIds: ["pim-artifact.service-map"],
            types: ["ServiceElementMembership", "OwnershipKind"],
            steps: [
              "Create ServiceElementMembership links from services to planned elements.",
              "Set OwnershipKind for each membership.",
            ],
            entryCriteria: ["Services defined"],
            exitCriteria: ["Memberships cover deployable boundaries"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
  {
    id: "pim.ph2",
    name: "Contracts & Data",
    order: 2,
    objective:
      "Define API/event contracts and persistent data architecture for the increment slice.",
    primaryRole: "solution-architect",
    entryCriteria: ["Architecture & Slice Framing complete"],
    exitCriteria: ["Contracts exist for APIs and events", "Persistent stores cover domain data"],
    inEngine: true,
    stages: [
      {
        id: "pim.ph2.st1",
        name: "Contracts & Schemas",
        objective:
          "Model schemas, validation constraints, and event envelopes aligned to CIM behavior.",
        primaryRole: "solution-architect",
        viewpoint: "contracts",
        tasks: [
          {
            id: "pim.ph2.st1.t1",
            name: "Define schemas and fields",
            primaryRole: "solution-architect",
            viewpoint: "contracts",
            artifactIds: ["pim-artifact.contract-catalog"],
            types: ["Schema", "SchemaField", "SchemaEnumLiteral", "SchemaKind", "FieldType"],
            steps: [
              "Create Schema elements with fields and enum literals.",
              "Set schema kind and field types aligned to CIM information items.",
            ],
            entryCriteria: ["Service boundaries defined"],
            exitCriteria: ["Schemas cover API and message payloads"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "pim.ph2.st1.t2",
            name: "Model event types and envelopes",
            primaryRole: "solution-architect",
            viewpoint: "contracts",
            artifactIds: ["pim-artifact.contract-catalog"],
            types: [
              "EventType",
              "EventEnvelope",
              "SchemaValidationConstraint",
              "SchemaConstraint",
              "SchemaCompatibility",
            ],
            steps: [
              "Define EventType and EventEnvelope elements from CIM events.",
              "Apply validation constraints and compatibility rules.",
            ],
            entryCriteria: ["Schemas defined"],
            exitCriteria: ["Event contracts aligned with CIM behavior surface"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "pim.ph2.st2",
        name: "Data Architecture",
        objective: "Model data stores, access patterns, and change streams for domain persistence.",
        primaryRole: "solution-architect",
        viewpoint: "data",
        tasks: [
          {
            id: "pim.ph2.st2.t1",
            name: "Model data stores and models",
            primaryRole: "solution-architect",
            viewpoint: "data",
            artifactIds: ["pim-artifact.data-architecture"],
            types: [
              "DataStore",
              "ObjectStore",
              "DataModel",
              "DataField",
              "StoreKind",
              "ConsistencyNeed",
            ],
            steps: [
              "Create DataStore and ObjectStore elements per service.",
              "Define DataModel and DataField structures from CIM entities.",
            ],
            entryCriteria: ["Contracts defined"],
            exitCriteria: ["Stores and models cover domain data"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "pim.ph2.st2.t2",
            name: "Define access patterns and indexes",
            primaryRole: "solution-architect",
            viewpoint: "data",
            artifactIds: ["pim-artifact.data-architecture"],
            types: [
              "AccessPattern",
              "IndexCandidate",
              "DataAccess",
              "DataAccessMode",
              "AccessPatternKind",
            ],
            steps: [
              "Model AccessPattern elements from CIM queries and commands.",
              "Define IndexCandidate and DataAccess bindings per store.",
            ],
            entryCriteria: ["Data models drafted"],
            exitCriteria: ["Access patterns cover read/write use cases"],
            validationRules: [],
            durationEstimate: "1h",
          },
          {
            id: "pim.ph2.st2.t3",
            name: "Configure change streams and notifications",
            primaryRole: "solution-architect",
            viewpoint: "data",
            artifactIds: ["pim-artifact.data-architecture"],
            types: ["DataChangeStream", "ObjectNotificationRule"],
            steps: [
              "Define DataChangeStream elements for event-sourced projections.",
              "Configure ObjectNotificationRule for object store triggers.",
            ],
            entryCriteria: ["Access patterns defined"],
            exitCriteria: ["Change streams linked to event contracts"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
  {
    id: "pim.ph3",
    name: "Compute & Exposure",
    order: 3,
    objective: "Define compute units and expose them through a coherent API surface.",
    primaryRole: "solution-architect",
    entryCriteria: ["Contracts & Data complete for slice"],
    exitCriteria: ["Functions cover behavioral surface", "Public API surface complete"],
    inEngine: true,
    stages: [
      {
        id: "pim.ph3.st1",
        name: "Compute Units",
        objective:
          "Define functions with contracts and triggers mapped to CIM commands and events.",
        primaryRole: "solution-architect",
        viewpoint: "compute",
        tasks: [
          {
            id: "pim.ph3.st1.t1",
            name: "Define functions and contracts",
            primaryRole: "solution-architect",
            viewpoint: "compute",
            artifactIds: ["pim-artifact.compute-catalog"],
            types: [
              "Function",
              "FunctionContract",
              "FunctionKind",
              "ComputeProfile",
              "ExecutionModel",
            ],
            steps: [
              "Create Function elements with FunctionContract bindings.",
              "Set compute profile and execution model per handler.",
            ],
            entryCriteria: ["Data architecture drafted"],
            exitCriteria: ["Functions mapped to CIM commands and queries"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "pim.ph3.st1.t2",
            name: "Configure triggers and runtime",
            primaryRole: "solution-architect",
            viewpoint: "compute",
            artifactIds: ["pim-artifact.compute-catalog"],
            types: ["Trigger", "RuntimeLanguage", "PackageManager"],
            steps: [
              "Define Trigger elements linking functions to events and schedules.",
              "Set runtime language and package manager per function.",
            ],
            entryCriteria: ["Functions defined"],
            exitCriteria: ["Triggers cover behavioral entry points"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "pim.ph3.st2",
        name: "API Surface",
        objective: "Expose functions through APIs with routes, contracts, and error mappings.",
        primaryRole: "solution-architect",
        viewpoint: "api",
        tasks: [
          {
            id: "pim.ph3.st2.t1",
            name: "Define APIs and routes",
            primaryRole: "solution-architect",
            viewpoint: "api",
            artifactIds: ["pim-artifact.api-catalog"],
            types: ["Api", "ApiRoute", "ApiStyle", "HttpMethod", "InvocationMode"],
            steps: [
              "Create Api elements with routes and HTTP methods.",
              "Connect routes to function handlers.",
            ],
            entryCriteria: ["Compute units defined"],
            exitCriteria: ["API routes cover public endpoints"],
            validationRules: [],
            durationEstimate: "1h",
          },
          {
            id: "pim.ph3.st2.t2",
            name: "Map API contracts and errors",
            primaryRole: "solution-architect",
            viewpoint: "api",
            artifactIds: ["pim-artifact.api-catalog"],
            types: ["ApiContract", "ErrorMapping"],
            steps: [
              "Bind ApiContract elements to schema definitions.",
              "Map ErrorMapping responses to CIM business errors.",
            ],
            entryCriteria: ["API routes defined"],
            exitCriteria: ["Contracts and error mappings complete"],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
  {
    id: "pim.ph4",
    name: "Integration & Orchestration",
    order: 4,
    objective: "Wire async integration topology and long-running workflow orchestration.",
    primaryRole: "solution-architect",
    entryCriteria: ["Compute & Exposure complete for slice"],
    exitCriteria: ["Async integration topology complete", "Long-running processes orchestrated"],
    inEngine: true,
    stages: [
      {
        id: "pim.ph4.st1",
        name: "Integration Topology",
        objective: "Model event channels, flows, and routing rules connecting services.",
        primaryRole: "solution-architect",
        viewpoint: "integration",
        tasks: [
          {
            id: "pim.ph4.st1.t1",
            name: "Model event channels and buses",
            primaryRole: "solution-architect",
            viewpoint: "integration",
            artifactIds: ["pim-artifact.integration-topology"],
            types: [
              "EventChannel",
              "Queue",
              "Topic",
              "EventBus",
              "ChannelKind",
              "DeliverySemantics",
              "OrderingRequirement",
            ],
            steps: [
              "Create EventChannel, Queue, Topic, and EventBus elements.",
              "Set delivery semantics and ordering requirements.",
            ],
            entryCriteria: ["API surface defined"],
            exitCriteria: ["Channels cover async integration points"],
            validationRules: [],
            durationEstimate: "1h",
          },
          {
            id: "pim.ph4.st1.t2",
            name: "Define flows and routing rules",
            primaryRole: "solution-architect",
            viewpoint: "integration",
            artifactIds: ["pim-artifact.integration-topology"],
            types: [
              "Flow",
              "RequestResponseFlow",
              "EventFlow",
              "MessageFlow",
              "PubSubFlow",
              "OrchestrationFlow",
              "ExternalIntegrationFlow",
              "EventRoutingRule",
              "Schedule",
              "Subscription",
            ],
            steps: [
              "Model Flow variants connecting producers and consumers.",
              "Define EventRoutingRule and Subscription bindings.",
              "Configure Schedule triggers for periodic integration.",
            ],
            entryCriteria: ["Channels defined"],
            exitCriteria: ["Flows connect integration endpoints to functions"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
        ],
      },
      {
        id: "pim.ph4.st2",
        name: "Workflow Orchestration",
        objective: "Model workflows from CIM business processes with human tasks and compensation.",
        primaryRole: "solution-architect",
        viewpoint: "workflow",
        tasks: [
          {
            id: "pim.ph4.st2.t1",
            name: "Model workflows and states",
            primaryRole: "solution-architect",
            viewpoint: "workflow",
            artifactIds: ["pim-artifact.workflow-model"],
            types: [
              "Workflow",
              "WorkflowStep",
              "StartStep",
              "TaskStep",
              "ChoiceStep",
              "WaitStep",
              "SuccessEndStep",
              "FailureEndStep",
              "ParallelStep",
              "MapStep",
              "PassStep",
              "WorkflowTransition",
              "WorkflowKind",
            ],
            steps: [
              "Create Workflow elements from CIM business processes.",
              "Define typed workflow steps, transitions, and workflow kind.",
            ],
            entryCriteria: ["Integration topology defined"],
            exitCriteria: ["Workflows cover long-running CIM processes"],
            validationRules: [],
            durationEstimate: "1-2h",
          },
          {
            id: "pim.ph4.st2.t2",
            name: "Configure human tasks and error handling",
            primaryRole: "solution-architect",
            viewpoint: "workflow",
            artifactIds: ["pim-artifact.workflow-model"],
            types: [
              "HumanTask",
              "ApprovalTask",
              "EscalationPolicy",
              "CompensationPolicy",
              "ErrorHandler",
              "ParallelBranch",
              "MapStateConfig",
              "CallbackTaskConfig",
            ],
            steps: [
              "Add HumanTask and ApprovalTask elements with escalation policies.",
              "Define CompensationPolicy and ErrorHandler for failure paths.",
            ],
            entryCriteria: ["Workflows drafted"],
            exitCriteria: ["Human steps and error paths orchestrated"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
    ],
  },
  {
    id: "pim.ph5",
    name: "Assurance & Configuration",
    order: 5,
    objective:
      "Apply security, operational policies, and environment configuration across the slice.",
    primaryRole: "solution-architect",
    entryCriteria: ["Integration & Orchestration complete for slice"],
    exitCriteria: [
      "Auth model covers all public endpoints",
      "Operational policies applied",
      "External integrations and config complete",
    ],
    inEngine: true,
    stages: [
      {
        id: "pim.ph5.st1",
        name: "Security & Identity",
        objective:
          "Configure identity providers, principals, and authorization for APIs and functions.",
        primaryRole: "solution-architect",
        viewpoint: "security",
        tasks: [
          {
            id: "pim.ph5.st1.t1",
            name: "Configure identity providers and principals",
            primaryRole: "solution-architect",
            viewpoint: "security",
            artifactIds: ["pim-artifact.security-model"],
            types: ["IdentityProvider", "Principal", "IdentityKind", "PrincipalKind"],
            steps: [
              "Define IdentityProvider elements aligned to CIM actors.",
              "Register Principal elements for human and service identities.",
            ],
            entryCriteria: ["Workflow orchestration drafted"],
            exitCriteria: ["Identity model covers all actor types"],
            validationRules: [],
            durationEstimate: "45m",
          },
          {
            id: "pim.ph5.st1.t2",
            name: "Define permissions and security policies",
            primaryRole: "solution-architect",
            viewpoint: "security",
            artifactIds: ["pim-artifact.security-model"],
            types: [
              "Permission",
              "SecurityPolicy",
              "AuthPolicy",
              "AuthorizationPolicy",
              "PermissionEffect",
              "PermissionActionKind",
              "LeastPrivilegeStatus",
            ],
            steps: [
              "Create Permission elements with effect and action kind.",
              "Apply AuthPolicy and AuthorizationPolicy to APIs and functions.",
            ],
            entryCriteria: ["Principals configured"],
            exitCriteria: ["Auth model covers all public endpoints"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "pim.ph5.st2",
        name: "Architecture Policies",
        objective:
          "Apply resilience, observability, governance, and cost policies to architecture elements.",
        primaryRole: "solution-architect",
        viewpoint: "policies",
        subStages: [
          {
            id: "pim.ph5.st2.ss1",
            name: "Resilience & Throughput",
            objective: "Configure retry, timeout, concurrency, and throughput policies.",
            primaryRole: "solution-architect",
            viewpoint: "policies",
            tasks: [
              {
                id: "pim.ph5.st2.ss1.t1",
                name: "Apply resilience policies",
                primaryRole: "solution-architect",
                viewpoint: "policies",
                artifactIds: ["pim-artifact.policy-catalog"],
                types: [
                  "ResiliencePolicy",
                  "RetryPolicy",
                  "DeadLetterPolicy",
                  "TimeoutPolicy",
                  "IdempotencyPolicy",
                ],
                steps: [
                  "Define ResiliencePolicy on functions and integration flows.",
                  "Configure RetryPolicy, DeadLetterPolicy, and TimeoutPolicy per target.",
                  "Set IdempotencyPolicy for state-changing handlers.",
                ],
                entryCriteria: ["Security and identity configured"],
                exitCriteria: ["Resilience policies applied to critical paths"],
                validationRules: [],
                durationEstimate: "1h",
              },
              {
                id: "pim.ph5.st2.ss1.t2",
                name: "Configure throughput and ordering policies",
                primaryRole: "solution-architect",
                viewpoint: "policies",
                artifactIds: ["pim-artifact.policy-catalog"],
                types: [
                  "ConcurrencyPolicy",
                  "RateLimitPolicy",
                  "BatchPolicy",
                  "OrderingPolicy",
                  "CachePolicy",
                  "BackupPolicy",
                  "RetentionPolicy",
                  "CostPolicy",
                ],
                steps: [
                  "Set ConcurrencyPolicy and RateLimitPolicy on APIs and functions.",
                  "Configure BatchPolicy, OrderingPolicy, and CachePolicy where needed.",
                  "Apply BackupPolicy, RetentionPolicy, and CostPolicy to stores.",
                ],
                entryCriteria: ["Resilience policies applied"],
                exitCriteria: ["Throughput and cost policies configured"],
                validationRules: [],
                durationEstimate: "45m",
              },
            ],
          },
          {
            id: "pim.ph5.st2.ss2",
            name: "Observability & SLOs",
            objective: "Configure logging, metrics, tracing, alerts, and service level objectives.",
            primaryRole: "solution-architect",
            viewpoint: "policies",
            tasks: [
              {
                id: "pim.ph5.st2.ss2.t1",
                name: "Configure observability policies",
                primaryRole: "solution-architect",
                viewpoint: "policies",
                artifactIds: ["pim-artifact.policy-catalog"],
                types: [
                  "ObservabilityConfig",
                  "LoggingPolicy",
                  "MetricPolicy",
                  "MetricDimension",
                  "TracingPolicy",
                ],
                steps: [
                  "Define ObservabilityConfig per service.",
                  "Apply LoggingPolicy, MetricPolicy, and TracingPolicy to functions and APIs.",
                ],
                entryCriteria: ["Resilience policies applied"],
                exitCriteria: ["Observability baseline configured"],
                validationRules: [],
                durationEstimate: "45m",
              },
              {
                id: "pim.ph5.st2.ss2.t2",
                name: "Define alerts, SLOs, and CORS",
                primaryRole: "solution-architect",
                viewpoint: "policies",
                artifactIds: ["pim-artifact.policy-catalog"],
                types: ["AlertPolicy", "Slo", "CorsPolicy"],
                steps: [
                  "Create AlertPolicy and Slo elements for critical endpoints.",
                  "Apply CorsPolicy to public API routes.",
                ],
                entryCriteria: ["Observability baseline configured"],
                exitCriteria: ["Alerts and SLOs cover critical paths"],
                validationRules: [],
                durationEstimate: "30m",
              },
            ],
          },
          {
            id: "pim.ph5.st2.ss3",
            name: "Governance & Business Rules",
            objective: "Apply data protection, compliance, and business rule policies.",
            primaryRole: "solution-architect",
            viewpoint: "policies",
            tasks: [
              {
                id: "pim.ph5.st2.ss3.t1",
                name: "Apply governance and compliance policies",
                primaryRole: "solution-architect",
                viewpoint: "policies",
                artifactIds: ["pim-artifact.policy-catalog"],
                types: [
                  "ArchitecturePolicy",
                  "PolicySetting",
                  "DataProtectionPolicy",
                  "DataQualityPolicy",
                  "CompliancePolicy",
                ],
                steps: [
                  "Define ArchitecturePolicy and PolicySetting elements.",
                  "Apply DataProtectionPolicy and CompliancePolicy from CIM governance.",
                ],
                entryCriteria: ["Observability policies configured"],
                exitCriteria: ["Governance policies linked to data and APIs"],
                validationRules: [],
                durationEstimate: "45m",
              },
              {
                id: "pim.ph5.st2.ss3.t2",
                name: "Map business rules and decision models",
                primaryRole: "solution-architect",
                viewpoint: "policies",
                artifactIds: ["pim-artifact.policy-catalog"],
                types: ["BusinessRule", "DecisionModel", "DecisionRule"],
                steps: [
                  "Create BusinessRule elements from CIM policies.",
                  "Model DecisionModel with DecisionRule rows for branching logic.",
                ],
                entryCriteria: ["Governance policies applied"],
                exitCriteria: ["Business rules linked to functions and workflows"],
                validationRules: [],
                durationEstimate: "45m",
              },
            ],
          },
        ],
      },
      {
        id: "pim.ph5.st3",
        name: "External & Config",
        objective: "Model external integrations, environments, secrets, and deployment units.",
        primaryRole: "solution-architect",
        viewpoint: "config",
        tasks: [
          {
            id: "pim.ph5.st3.t1",
            name: "Model external endpoints and adapters",
            primaryRole: "solution-architect",
            viewpoint: "config",
            artifactIds: ["pim-artifact.config-package"],
            types: ["ExternalEndpoint", "ExternalAdapter", "SupportLevel"],
            steps: [
              "Create ExternalEndpoint elements from CIM external systems.",
              "Define ExternalAdapter bindings to integration flows.",
            ],
            entryCriteria: ["Architecture policies applied"],
            exitCriteria: ["External integrations modeled"],
            validationRules: [],
            durationEstimate: "45m",
          },
          {
            id: "pim.ph5.st3.t2",
            name: "Configure environments and deployment units",
            primaryRole: "solution-architect",
            viewpoint: "config",
            artifactIds: ["pim-artifact.config-package"],
            types: [
              "Environment",
              "DeploymentUnit",
              "ConfigurationSet",
              "ConfigParameter",
              "EnvironmentVariable",
              "Secret",
              "CredentialRequirement",
              "SecretKind",
              "ConfigScope",
              "EnvironmentClass",
              "DeploymentUnitType",
            ],
            steps: [
              "Define Environment and DeploymentUnit elements per stage.",
              "Configure ConfigurationSet, secrets, and credential requirements.",
              "Set ConfigParameter and EnvironmentVariable values per environment.",
            ],
            entryCriteria: ["External integrations modeled"],
            exitCriteria: ["Environments and config complete for slice"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
    ],
  },
  {
    id: "pim.ph6",
    name: "Platform Readiness",
    order: 6,
    objective: "Assess platform capability mapping, close traceability, and pass PIM EVL gate.",
    primaryRole: "process-reviewer",
    entryCriteria: ["Assurance & Configuration complete for slice"],
    exitCriteria: [
      "PIM EVL passes",
      "Readiness gate approved",
      "PIM increment reviewed and improvement actions captured",
    ],
    inEngine: true,
    stages: [
      {
        id: "pim.ph6.st1",
        name: "Platform Mapping Assessment",
        objective: "Evaluate platform capability coverage and mapping readiness.",
        primaryRole: "process-reviewer",
        viewpoint: "readiness",
        tasks: [
          {
            id: "pim.ph6.st1.t1",
            name: "Assess platform capabilities",
            primaryRole: "process-reviewer",
            viewpoint: "readiness",
            artifactIds: ["pim-artifact.platform-readiness"],
            types: ["PlatformCapability", "PlatformMappingAssessment"],
            steps: [
              "Review PlatformCapability coverage against modeled elements.",
              "Complete PlatformMappingAssessment with gap analysis.",
            ],
            entryCriteria: ["External and config complete"],
            exitCriteria: ["Platform mapping assessment documented"],
            validationRules: [],
            durationEstimate: "1h",
          },
        ],
      },
      {
        id: "pim.ph6.st2",
        name: "Trace & Readiness Gate",
        objective: "Close trace links and production readiness before PIM→PSM transform.",
        primaryRole: "process-reviewer",
        viewpoint: "readiness",
        tasks: [
          {
            id: "pim.ph6.st2.t1",
            name: "Complete trace and readiness",
            primaryRole: "process-reviewer",
            viewpoint: "readiness",
            artifactIds: ["pim-artifact.platform-readiness"],
            types: [],
            readinessTypes: true,
            steps: [
              "Build TraceModel links across CIM and PIM elements.",
              "Complete ProductionReadinessAssessment and resolve findings.",
            ],
            entryCriteria: ["Platform mapping assessment complete"],
            exitCriteria: ["PIM EVL passes; readiness gate approved"],
            validationRules: ["pim-semantic-validation"],
            durationEstimate: "1-2h",
          },
        ],
      },
      {
        id: "pim.ph6.st3",
        name: "Increment Review & Adapt",
        objective:
          "Review the service slice architecture, accept the increment, and adapt the next cycle.",
        primaryRole: "process-reviewer",
        viewpoint: "readiness",
        tasks: [
          {
            id: "pim.ph6.st3.t1",
            name: "Review and adapt PIM increment",
            primaryRole: "process-reviewer",
            viewpoint: "readiness",
            artifactIds: ["pim-artifact.increment-review"],
            types: [],
            steps: [
              "Review architecture outcomes against CIM trace links and PIM definition of done.",
              "Record accepted scope, deferred architecture decisions, and platform mapping feedback.",
              "Create improvement actions and backlog adjustments for the next service slice.",
            ],
            entryCriteria: ["PIM EVL passes or all blocking findings are dispositioned"],
            exitCriteria: [
              "Increment accepted or rework loop selected; improvement actions captured",
            ],
            validationRules: [],
            durationEstimate: "45m",
          },
        ],
      },
    ],
  },
];
