export const CANVAS_SIZE = {
  width: 1000,
  height: 620,
};

export const models = {
  cim: {
    name: "Signal Desk CIM",
    nodes: [
      {
        id: "customer",
        type: "Actor",
        tag: "ACT",
        name: "Customer",
        icon: "A",
        color: "#b497ff",
        x: 110,
        y: 310,
        properties: [
          ["actorType", "EXTERNAL_USER"],
          ["trustLevel", "UNTRUSTED"],
        ],
      },
      {
        id: "support-capability",
        type: "BusinessCapability",
        tag: "CAP",
        name: "Support Intake",
        icon: "C",
        color: "#b7ff54",
        x: 320,
        y: 135,
        properties: [
          ["criticality", "CORE"],
          ["owner", "Support team"],
        ],
      },
      {
        id: "support-ticket",
        type: "DomainEntity",
        tag: "DOM",
        name: "SupportTicket",
        icon: "D",
        color: "#4ce6e0",
        x: 610,
        y: 145,
        properties: [
          ["identity", "ticketId"],
          ["attributes", "subject, status"],
        ],
      },
      {
        id: "ticket-aggregate",
        type: "AggregateCandidate",
        tag: "AGG",
        name: "TicketAggregate",
        icon: "G",
        color: "#4ce6e0",
        x: 820,
        y: 320,
        properties: [
          ["root", "SupportTicket"],
          ["consistency", "STRONG"],
        ],
      },
      {
        id: "submit-ticket",
        type: "Command",
        tag: "CMD",
        name: "SubmitTicket",
        icon: "C",
        color: "#ffa828",
        x: 325,
        y: 440,
        properties: [
          ["intent", "Open a support ticket"],
          ["userInitiated", "true"],
        ],
      },
      {
        id: "ticket-submitted",
        type: "BusinessEvent",
        tag: "EVT",
        name: "TicketSubmitted",
        icon: "E",
        color: "#ff79b0",
        x: 610,
        y: 490,
        properties: [
          ["semanticVersion", "1.0.0"],
          ["auditRelevant", "true"],
        ],
      },
      {
        id: "get-ticket",
        type: "Query",
        tag: "QRY",
        name: "GetTicket",
        icon: "Q",
        color: "#71a7ff",
        x: 805,
        y: 125,
        properties: [
          ["queryType", "LOOKUP"],
          ["containsPersonalData", "false"],
        ],
      },
    ],
    edges: [
      {
        id: "customer-submits",
        source: "customer",
        target: "submit-ticket",
        label: "issues",
        kind: "request",
      },
      {
        id: "capability-contains-command",
        source: "support-capability",
        target: "submit-ticket",
        label: "contains",
        dashed: true,
      },
      {
        id: "command-targets-aggregate",
        source: "submit-ticket",
        target: "ticket-aggregate",
        label: "targets",
        kind: "request",
      },
      {
        id: "aggregate-root",
        source: "ticket-aggregate",
        target: "support-ticket",
        label: "root",
        kind: "data",
      },
      {
        id: "command-emits-event",
        source: "submit-ticket",
        target: "ticket-submitted",
        label: "results in",
        kind: "event",
      },
      {
        id: "query-reads-entity",
        source: "get-ticket",
        target: "support-ticket",
        label: "reads",
        kind: "data",
        dashed: true,
      },
    ],
  },
  pim: {
    name: "Signal Desk PIM",
    nodes: [
      {
        id: "support-api",
        type: "Api",
        tag: "API",
        name: "Support API",
        icon: "A",
        color: "#b497ff",
        x: 135,
        y: 220,
        properties: [
          ["apiStyle", "RESOURCE_HTTP"],
          ["route", "POST /tickets/submit-ticket"],
        ],
      },
      {
        id: "support-service",
        type: "ServerlessService",
        tag: "SVC",
        name: "Support Intake Service",
        icon: "S",
        color: "#b7ff54",
        x: 140,
        y: 450,
        properties: [
          ["boundary", "CAPABILITY_BASED"],
          ["ownsData", "true"],
        ],
      },
      {
        id: "submit-handler",
        type: "Function",
        tag: "FN",
        name: "SubmitTicket Handler",
        icon: "F",
        color: "#8dff55",
        x: 385,
        y: 175,
        properties: [
          ["kind", "COMMAND_HANDLER"],
          ["writesState", "true"],
        ],
      },
      {
        id: "get-ticket-handler",
        type: "Function",
        tag: "FN",
        name: "GetTicket Query Handler",
        icon: "F",
        color: "#71a7ff",
        x: 380,
        y: 445,
        properties: [
          ["kind", "QUERY_HANDLER"],
          ["readsState", "true"],
        ],
      },
      {
        id: "ticket-store",
        type: "DataStore",
        tag: "DATA",
        name: "TicketAggregate Store",
        icon: "D",
        color: "#4ce6e0",
        x: 655,
        y: 170,
        properties: [
          ["storeKind", "DOCUMENT"],
          ["consistency", "STRONG"],
        ],
      },
      {
        id: "ticket-event-type",
        type: "EventType",
        tag: "EVT",
        name: "TicketSubmitted",
        icon: "E",
        color: "#ff79b0",
        x: 795,
        y: 330,
        properties: [
          ["version", "1.0.0"],
          ["replayable", "true"],
        ],
      },
      {
        id: "notify-function",
        type: "Function",
        tag: "AI + FN",
        name: "NotifySupport Handler",
        icon: "F",
        color: "#8dff55",
        x: 625,
        y: 485,
        aiAddition: true,
        properties: [
          ["kind", "EVENT_HANDLER"],
          ["generatedBy", "AI assistant"],
        ],
      },
      {
        id: "notification-topic",
        type: "Topic",
        tag: "AI + TOPIC",
        name: "Support Notification Topic",
        icon: "T",
        color: "#ffa828",
        x: 810,
        y: 515,
        aiAddition: true,
        properties: [
          ["delivery", "AT_LEAST_ONCE"],
          ["generatedBy", "AI assistant"],
        ],
      },
    ],
    edges: [
      {
        id: "api-invokes-submit",
        source: "support-api",
        target: "submit-handler",
        label: "request/response",
        kind: "request",
      },
      {
        id: "service-owns-submit",
        source: "support-service",
        target: "submit-handler",
        label: "owns",
        dashed: true,
      },
      {
        id: "service-owns-query",
        source: "support-service",
        target: "get-ticket-handler",
        label: "owns",
        dashed: true,
      },
      {
        id: "submit-writes-store",
        source: "submit-handler",
        target: "ticket-store",
        label: "writes",
        kind: "data",
      },
      {
        id: "query-reads-store",
        source: "get-ticket-handler",
        target: "ticket-store",
        label: "reads",
        kind: "data",
        dashed: true,
      },
      {
        id: "submit-publishes-event",
        source: "submit-handler",
        target: "ticket-event-type",
        label: "publishes",
        kind: "event",
      },
      {
        id: "event-routes-topic",
        source: "ticket-event-type",
        target: "notification-topic",
        label: "pub/sub flow",
        kind: "event",
        aiAddition: true,
      },
      {
        id: "topic-invokes-notify",
        source: "notification-topic",
        target: "notify-function",
        label: "subscription",
        kind: "event",
        aiAddition: true,
      },
    ],
  },
  psm: {
    name: "Signal Desk AWS PSM",
    nodes: [
      {
        id: "http-api",
        type: "HttpApi",
        tag: "AWS API",
        name: "SignalDeskHttpApi",
        icon: "A",
        color: "#b497ff",
        x: 135,
        y: 215,
        properties: [
          ["awsType", "AWS::Serverless::HttpApi"],
          ["routeKey", "POST /tickets/submit-ticket"],
        ],
      },
      {
        id: "cloudwatch",
        type: "CloudWatchAlarm",
        tag: "AWS CW",
        name: "SubmitTicketErrors",
        icon: "W",
        color: "#71a7ff",
        x: 150,
        y: 470,
        properties: [
          ["metric", "Errors"],
          ["threshold", "1"],
        ],
      },
      {
        id: "submit-lambda",
        type: "AwsLambdaFunction",
        tag: "AWS LAMBDA",
        name: "SubmitTicketFunction",
        icon: "L",
        color: "#ffa828",
        x: 400,
        y: 175,
        manualTarget: true,
        properties: [
          ["memorySizeMb", "256 -> 512"],
          ["architecture", "ARM64"],
        ],
      },
      {
        id: "lambda-role",
        type: "IamRole",
        tag: "AWS IAM",
        name: "SubmitTicketRole",
        icon: "I",
        color: "#ff7d36",
        x: 385,
        y: 455,
        properties: [
          ["effect", "ALLOW"],
          ["leastPrivilege", "REVIEWED"],
        ],
      },
      {
        id: "ticket-table",
        type: "DynamoDbTable",
        tag: "AWS DDB",
        name: "TicketAggregateTable",
        icon: "D",
        color: "#4ce6e0",
        x: 655,
        y: 165,
        properties: [
          ["billingMode", "PAY_PER_REQUEST"],
          ["PITR", "enabled"],
        ],
      },
      {
        id: "support-topic",
        type: "SnsTopic",
        tag: "AWS SNS",
        name: "SupportNotificationTopic",
        icon: "S",
        color: "#ff79b0",
        x: 805,
        y: 345,
        properties: [
          ["awsType", "AWS::SNS::Topic"],
          ["encrypted", "true"],
        ],
      },
      {
        id: "notify-lambda",
        type: "AwsLambdaFunction",
        tag: "AWS LAMBDA",
        name: "NotifySupportFunction",
        icon: "L",
        color: "#ffa828",
        x: 650,
        y: 495,
        properties: [
          ["trigger", "SNS subscription"],
          ["tracing", "ACTIVE"],
        ],
      },
    ],
    edges: [
      {
        id: "http-integration",
        source: "http-api",
        target: "submit-lambda",
        label: "API Gateway integration",
        kind: "request",
      },
      {
        id: "lambda-table-access",
        source: "submit-lambda",
        target: "ticket-table",
        label: "PutItem",
        kind: "data",
      },
      {
        id: "lambda-publishes-sns",
        source: "submit-lambda",
        target: "support-topic",
        label: "Publish",
        kind: "event",
      },
      {
        id: "sns-invokes-lambda",
        source: "support-topic",
        target: "notify-lambda",
        label: "SNS subscription",
        kind: "event",
      },
      {
        id: "role-grants-lambda",
        source: "lambda-role",
        target: "submit-lambda",
        label: "execution role",
        dashed: true,
      },
      {
        id: "alarm-monitors-lambda",
        source: "cloudwatch",
        target: "submit-lambda",
        label: "monitors",
        dashed: true,
      },
    ],
  },
};

export const transformationBatches = [
  {
    id: "cim-pim",
    rules: [
      {label: "TR-070 Command -> Function", x: 3, y: 12, color: "#ffa828"},
      {label: "TR-040 Entity -> Schema", x: 60, y: 7, color: "#4ce6e0"},
      {label: "TR-050 Aggregate -> DataStore", x: 64, y: 78, color: "#4ce6e0"},
      {label: "TR-090 Event -> EventType", x: 1, y: 80, color: "#ff79b0"},
    ],
    inputs: [
      ["CMD", "#ffa828"],
      ["DOM", "#4ce6e0"],
      ["AGG", "#4ce6e0"],
      ["EVT", "#ff79b0"],
      ["QRY", "#71a7ff"],
    ],
    outputs: [
      ["FN", "#8dff55"],
      ["API", "#b497ff"],
      ["STORE", "#4ce6e0"],
      ["SCHEMA", "#4ce6e0"],
      ["EVENT", "#ff79b0"],
    ],
  },
  {
    id: "pim-psm",
    rules: [
      {label: "Function -> AWS Lambda", x: 2, y: 12, color: "#ffa828"},
      {label: "Api -> HTTP API", x: 64, y: 8, color: "#b497ff"},
      {label: "DataStore -> DynamoDB", x: 64, y: 79, color: "#4ce6e0"},
      {label: "Topic -> SNS Topic", x: 2, y: 81, color: "#ff79b0"},
    ],
    inputs: [
      ["FN", "#8dff55"],
      ["API", "#b497ff"],
      ["STORE", "#4ce6e0"],
      ["TOPIC", "#ffa828"],
      ["FLOW", "#ff79b0"],
    ],
    outputs: [
      ["LAMBDA", "#ffa828"],
      ["HTTP API", "#b497ff"],
      ["DDB", "#4ce6e0"],
      ["SNS", "#ff79b0"],
      ["IAM", "#ff7d36"],
    ],
  },
  {
    id: "psm-artifacts",
    rules: [
      {label: "Lambda -> Go handler", x: 2, y: 12, color: "#71a7ff"},
      {label: "SamStack -> template.yaml", x: 59, y: 8, color: "#ffa828"},
      {label: "Api -> OpenAPI", x: 66, y: 79, color: "#b497ff"},
      {label: "Trace -> reports", x: 3, y: 81, color: "#b7ff54"},
    ],
    inputs: [
      ["LAMBDA", "#ffa828"],
      ["HTTP API", "#b497ff"],
      ["DDB", "#4ce6e0"],
      ["SNS", "#ff79b0"],
      ["IAM", "#ff7d36"],
    ],
    outputs: [
      ["handler.go", "#71a7ff"],
      ["template.yaml", "#ffa828"],
      ["openapi.yaml", "#b497ff"],
      ["tests", "#8dff55"],
      ["trace.json", "#b7ff54"],
    ],
  },
];

export const artifactTree = [
  {name: ".github", type: "folder", depth: 0, color: "#b497ff"},
  {name: "workflows", type: "folder", depth: 1, color: "#b497ff"},
  {name: "validate.yml", type: "file", depth: 2, color: "#b497ff"},
  {name: "docs", type: "folder", depth: 0, color: "#71a7ff"},
  {name: "architecture.md", type: "file", depth: 1, color: "#71a7ff"},
  {name: "traceability.md", type: "file", depth: 1, color: "#71a7ff"},
  {name: "schemas", type: "folder", depth: 0, color: "#ff79b0"},
  {name: "openapi.yaml", type: "file", depth: 1, color: "#ff79b0"},
  {name: "src", type: "folder", depth: 0, color: "#8dff55"},
  {name: "functions", type: "folder", depth: 1, color: "#8dff55"},
  {name: "submit-ticket", type: "folder", depth: 2, color: "#8dff55"},
  {name: "handler.go", type: "file", depth: 3, color: "#71a7ff", active: true},
  {name: "notify-support", type: "folder", depth: 2, color: "#8dff55"},
  {name: "handler.go", type: "file", depth: 3, color: "#71a7ff"},
  {name: "shared", type: "folder", depth: 1, color: "#8dff55"},
  {name: "data-access.go", type: "file", depth: 2, color: "#71a7ff"},
  {name: "event-publisher.go", type: "file", depth: 2, color: "#71a7ff"},
  {name: "tests", type: "folder", depth: 0, color: "#4ce6e0"},
  {name: "template.yaml", type: "file", depth: 0, color: "#ffa828"},
  {name: "samconfig.toml", type: "file", depth: 0, color: "#ffa828"},
  {name: "go.mod", type: "file", depth: 0, color: "#71a7ff"},
];

export const codeLines = [
  {
    html: '<span class="token-keyword">package</span> main',
  },
  {
    html: "",
  },
  {
    html: '<span class="token-keyword">import</span> (',
  },
  {
    html: '  <span class="token-string">"context"</span>',
  },
  {
    html: '  <span class="token-string">"github.com/aws/aws-lambda-go/lambda"</span>',
  },
  {
    html: ")",
  },
  {
    html: "",
  },
  {
    html: '<span class="token-keyword">func</span> Handler(ctx context.Context, evt map[<span class="token-keyword">string</span>]any) (GeneratedResult, <span class="token-keyword">error</span>) {',
  },
  {
    html: "  correlationID := shared.ExtractCorrelationID(evt)",
  },
  {
    html: "  logObj := shared.NewLogger(correlationID, <span class=\"token-string\">\"SubmitTicket\"</span>, configObj.Stage)",
  },
  {
    html: "  <span class=\"token-comment\">// validation, tracing, metrics, and idempotency are generated</span>",
  },
  {
    html: "",
  },
  {
    html: "  <span class=\"token-comment\">/* protected region submit-ticket-function.business-logic on begin */</span>",
    className: "protected",
  },
  {
    html: "  <span class=\"token-comment\">// TODO: add developer-owned business logic.</span>",
    className: "todo-code",
  },
  {
    html: "  <span class=\"token-keyword\">return</span> GeneratedResult{}, shared.NewGeneratedHandlerError(<span class=\"token-string\">\"NOT_IMPLEMENTED\"</span>)",
    className: "todo-code",
  },
  {
    html: "  ticket := map[<span class=\"token-keyword\">string</span>]any{",
    className: "manual-code",
  },
  {
    html: "    <span class=\"token-string\">\"subject\"</span>: validatedInput.Payload,",
    className: "manual-code",
  },
  {
    html: "    <span class=\"token-string\">\"status\"</span>: <span class=\"token-string\">\"OPEN\"</span>,",
    className: "manual-code",
  },
  {
    html: "    <span class=\"token-string\">\"correlationId\"</span>: correlationID,",
    className: "manual-code",
  },
  {
    html: "  }",
    className: "manual-code",
  },
  {
    html: "  <span class=\"token-keyword\">return</span> GeneratedResult{StatusCode: <span class=\"token-number\">201</span>, Body: ticket}, <span class=\"token-keyword\">nil</span>",
    className: "manual-code",
  },
  {
    html: "  <span class=\"token-comment\">/* protected region submit-ticket-function.business-logic end */</span>",
    className: "protected",
  },
  {
    html: "",
  },
  {
    html: "  <span class=\"token-comment\">// modeled events are published by generated runtime code</span>",
  },
  {
    html: "  logObj.Info(<span class=\"token-string\">\"ticket submitted\"</span>, ticket)",
  },
  {
    html: "}",
  },
  {
    html: "",
  },
  {
    html: '<span class="token-keyword">func</span> main() { lambda.Start(Handler) }',
  },
];

export const phases = [
  {id: "cim", label: "CIM model", level: "cim", count: "01 / 08", start: 0},
  {
    id: "cim-pim",
    label: "CIM to PIM",
    level: "pim",
    count: "02 / 08",
    start: 0.105
  },
  {
    id: "assistant",
    label: "AI assistant",
    level: "pim",
    count: "03 / 08",
    start: 0.28
  },
  {
    id: "pim-psm",
    label: "PIM to AWS PSM",
    level: "psm",
    count: "04 / 08",
    start: 0.39
  },
  {
    id: "refine",
    label: "Manual refinement",
    level: "psm",
    count: "05 / 08",
    start: 0.57
  },
  {
    id: "generate",
    label: "PSM to artifacts",
    level: "artifacts",
    count: "06 / 08",
    start: 0.665
  },
  {
    id: "protected",
    label: "Protected region",
    level: "artifacts",
    count: "07 / 08",
    start: 0.805
  },
  {
    id: "ready",
    label: "Ready to deploy",
    level: "artifacts",
    count: "08 / 08",
    start: 0.91
  },
];
