logging:
  structured:
    format:
      console: logstash
    json:
      add:
        service: ${spring.application.name}
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    io.mehdieidi.modriss: INFO
