function normalizeBaseUrl(value) {
  if (!value) {
    return "";
  }
  return String(value).trim().replace(/\/+$/, "");
}

export const backendBaseUrl = normalizeBaseUrl(window.FUNC2_BACKEND_BASE_URL);
export const backendOrigin = backendBaseUrl || window.location.origin;
export const apiBase = backendBaseUrl ? `${backendBaseUrl}/api` : "/api";

export function apiUrl(path) {
  const normalizedPath = path.startsWith("/") ? path : `/${path}`;
  return `${apiBase}${normalizedPath}`;
}

export function websocketUrl(path) {
  const normalizedPath = path.startsWith("/") ? path : `/${path}`;
  const backend = new URL(backendOrigin);
  const protocol = backend.protocol === "https:" ? "wss:" : "ws:";
  return `${protocol}//${backend.host}${normalizedPath}`;
}

export const DEFAULT_AWS_ACCOUNT_ID = "000000000000";
export const DEFAULT_AWS_REGION = "us-east-1";
export const CHAT_ATTACHMENT_MAX_BYTES = 300000;
export const LOG_HINT = "See backend logs (default path: logs/func2-backend.log)";
export const MOBILE_BREAKPOINT = 768;
export const TOUCH_MOVE_THRESHOLD = 6;

export const MODEL_TYPES = {
  cim: {
    apiType: "cim",
    chatType: "CIM",
    palette: [
      "BusinessGoal",
      "Objective",
      "KPI",
      "StakeholderConcern",
      "Actor",
      "Role",
      "Persona",
      "ExternalSystem",
      "BusinessCapability",
      "CapabilityDependency",
      "BoundedContextCandidate",
      "AggregateCandidate",
      "Command",
      "Query",
      "BusinessEvent",
      "BusinessProcess",
      "ProcessStep",
      "Decision",
      "Precondition",
      "Postcondition",
      "ExceptionScenario",
      "TemporalConstraint",
      "Policy",
      "DomainEntity",
      "ValueObject",
      "DomainRelationship",
      "InformationItem",
      "DataClassification",
      "ConsentRequirement",
      "NonFunctionalRequirement",
      "QualityScenario",
      "SecurityConstraint",
      "PrivacyConstraint",
      "RegulatoryConstraint",
      "Hotspot",
      "OpenQuestion",
      "Risk",
      "RequirementLink",
      "GoalSatisfactionLink",
      "Assumption"
    ],
    connectionKinds: [
      "PRECEDES",
      "TRIGGERS",
      "EMITS",
      "READS",
      "CAUSES",
      "ISSUED_BY",
      "HANDLED_BY",
      "CONSUMED_BY",
      "GUARDS",
      "CONTAINS",
      "SUPPORTS",
      "CONSTRAINS",
      "ASSOCIATED_WITH",
      "REFINES",
      "MEASURES",
      "OWNS",
      "WRITES",
      "DEPENDS_ON",
      "CLASSIFIED_AS",
      "SATISFIES",
      "USES"
    ]
  },
  pim: {
    apiType: "pim",
    chatType: "PIM",
    palette: [
      "Function",
      "FunctionContract",
      "Api",
      "ApiRoute",
      "EventSource",
      "Trigger",
      "EventChannel",
      "EventRoutingRule",
      "Queue",
      "Topic",
      "EventBus",
      "EventType",
      "ServerlessService",
      "DeploymentUnit",
      "Workflow",
      "WorkflowState",
      "Flow",
      "RequestResponseFlow",
      "EventFlow",
      "MessageFlow",
      "OrchestrationFlow",
      "DataStore",
      "ObjectStore",
      "IdentityProvider",
      "Principal",
      "Permission",
      "Secret",
      "ConfigParameter",
      "EnvironmentVariable",
      "ResiliencePolicy",
      "ObservabilityConfig",
      "IdempotencyPolicy",
      "ConcurrencyPolicy",
      "CostPolicy"
    ],
    connectionKinds: [
      "OWNS",
      "DEPLOYS",
      "INVOKES",
      "TRIGGERS",
      "PUBLISHES",
      "SUBSCRIBES_TO",
      "READS",
      "WRITES",
      "INTEGRATES_WITH",
      "USES_SECRET",
      "HAS_ENV",
      "AUTHENTICATES",
      "GRANTS",
      "GOVERNS",
      "ORCHESTRATES",
      "ROUTES_TO",
      "BELONGS_TO",
      "ATTACHED_TO",
      "USES",
      "CONTAINS"
    ]
  },
  psm: {
    apiType: "psm",
    chatType: "PSM",
    palette: [
      "AwsLambdaFunction",
      "ApiGatewayTrigger",
      "SqsLambdaEventSourceMapping",
      "EventBridgeLambdaTarget",
      "ApiGatewayApi",
      "ApiGatewayRoute",
      "EventBridgeBus",
      "EventBridgeRule",
      "SqsQueue",
      "SnsTopic",
      "EventSchema",
      "StepFunctionStateMachine",
      "DynamoDbTable",
      "DynamoDbAttributeDefinition",
      "DynamoDbGlobalSecondaryIndex",
      "S3Bucket",
      "SamStack",
      "AwsStage",
      "LambdaEventSourceMapping",
      "CognitoUserPool",
      "IamPolicy",
      "IamStatement",
      "IamRole",
      "SecretsManagerSecret",
      "SsmParameter",
      "KmsKey",
      "VpcConfig",
      "EnvironmentConfig",
      "LambdaEnvironmentVariable",
      "CloudWatchAlarm",
      "CloudWatchLogGroup",
      "XRayTracingConfig"
    ],
    connectionKinds: [
      "CONTAINS",
      "DEPENDS_ON",
      "TRIGGERS",
      "MAPS_TO",
      "INTEGRATES_WITH",
      "USES_ROLE",
      "WRITES_LOGS_TO",
      "READS_FROM",
      "WRITES_TO",
      "ENCRYPTED_BY",
      "PUBLISHED_TO",
      "TARGETS",
      "DEPLOYED_IN",
      "HAS_ENV",
      "AUTHORIZED_BY"
    ]
  }
};

export const NODE_ICONS = {
  BusinessGoal: "flag",
  Objective: "track_changes",
  KPI: "analytics",
  StakeholderConcern: "report",
  Actor: "person",
  Role: "badge",
  Persona: "face",
  ExternalSystem: "language",
  BusinessCapability: "track_changes",
  CapabilityDependency: "link",
  BoundedContextCandidate: "hub",
  DomainEntity: "category",
  ValueObject: "data_object",
  AggregateCandidate: "account_tree",
  DomainRelationship: "join_full",
  InformationItem: "description",
  DataClassification: "privacy_tip",
  ConsentRequirement: "task_alt",
  BusinessProcess: "schema",
  ProcessStep: "stairs",
  Command: "play_arrow",
  Query: "search",
  BusinessEvent: "bolt",
  Policy: "gavel",
  Decision: "alt_route",
  Precondition: "rule",
  Postcondition: "check_circle",
  ExceptionScenario: "error",
  TemporalConstraint: "schedule",
  NonFunctionalRequirement: "rule",
  QualityScenario: "monitor_heart",
  SecurityConstraint: "security",
  PrivacyConstraint: "shield",
  RegulatoryConstraint: "balance",
  Hotspot: "local_fire_department",
  RequirementLink: "link",
  GoalSatisfactionLink: "done_all",
  Assumption: "help",
  Risk: "warning",
  OpenQuestion: "help",
  Function: "functions",
  FunctionContract: "description",
  EventSource: "input",
  Trigger: "play_lesson",
  Api: "api",
  ApiRoute: "route",
  EventType: "description",
  EventChannel: "alt_route",
  Queue: "queue",
  Topic: "campaign",
  EventBus: "hub",
  EventRoutingRule: "account_tree",
  Workflow: "schema",
  WorkflowState: "timeline",
  Flow: "east",
  RequestResponseFlow: "sync_alt",
  EventFlow: "shuffle",
  MessageFlow: "mail",
  OrchestrationFlow: "account_tree",
  ServerlessService: "domain",
  DeploymentUnit: "inventory_2",
  DataStore: "database",
  ObjectStore: "folder_zip",
  IdentityProvider: "verified_user",
  Principal: "group",
  Permission: "policy",
  Secret: "key",
  ConfigParameter: "tune",
  EnvironmentVariable: "settings",
  ObservabilityConfig: "monitoring",
  ResiliencePolicy: "shield",
  IdempotencyPolicy: "repeat",
  ConcurrencyPolicy: "groups",
  CostPolicy: "savings",
  AwsStage: "layers",
  SamStack: "inventory",
  AwsLambdaFunction: "functions",
  LambdaEventSourceMapping: "link",
  SqsLambdaEventSourceMapping: "link",
  ApiGatewayTrigger: "link",
  EventBridgeLambdaTarget: "track_changes",
  ApiGatewayApi: "api",
  ApiGatewayRoute: "route",
  EventBridgeBus: "hub",
  EventBridgeRule: "rule",
  SqsQueue: "queue",
  SnsTopic: "campaign",
  EventSchema: "rule",
  StepFunctionStateMachine: "alt_route",
  DynamoDbTable: "table_rows",
  DynamoDbAttributeDefinition: "list_alt",
  DynamoDbGlobalSecondaryIndex: "view_list",
  S3Bucket: "folder_zip",
  CognitoUserPool: "supervised_user_circle",
  IamPolicy: "policy",
  IamStatement: "gavel",
  IamRole: "verified_user",
  CloudWatchLogGroup: "article",
  CloudWatchAlarm: "notifications",
  XRayTracingConfig: "timeline",
  SecretsManagerSecret: "key",
  SsmParameter: "tune",
  KmsKey: "vpn_key",
  VpcConfig: "lan",
  EnvironmentConfig: "settings",
  LambdaEnvironmentVariable: "settings_input_component"
};
