import { emptyDiagram } from "./utils.js";

// ── Mutable application state (singleton) ─────────────────────────────────────
export const state = {
  auth: {
    token: null,
    user: null,
  },
  project: null, // active Project object from backend
  activeType: "",
  modelId: null,
  modelRevision: 0,
  baseModel: null,
  modelSave: {
    dirty: false,
    saving: false,
    lastSavedAt: null,
    error: "",
  },
  diagram: emptyDiagram(""),
  nodesById: new Map(),
  connectionsById: new Map(),
  graph: {
    elementsById: new Map(),
    relationshipsById: new Map(),
    traceLinksById: new Map(),
    assumptionsById: new Map(),
    relationshipsBySource: new Map(),
    relationshipsByTarget: new Map(),
    relationshipsByKind: new Map(),
    containmentByParent: new Map(),
    parentByChild: new Map(),
  },
  views: {
    byId: new Map(),
    activeViewId: null,
    visibleNodeIds: new Set(),
    visibleRelationshipIds: new Set(),
    expandedContainers: new Set(),
  },
  fragments: {
    byId: new Map(),
    rootIds: [],
  },
  visibleGraph: emptyDiagram(""),
  modelingStrictness: "methodology",
  // Per-tab persisted state (save/restore on tab switch)
  tabs: {},
  modelsCache: {},
  modelingConfig: {
    config: null,
    draft: null,
  },
  viewport: { x: 0, y: 0, scale: 1 },
  connectMode: false,
  connectSourceId: null,
  preferredConnectionKind: null,
  linkDrag: null,
  dragNode: null,
  panDrag: null,
  touchTap: null,
  chat: {
    available: true,
    sessions: new Map(),
    channels: new Map(),
    attachment: null,
    historyOpen: false,
  },
  assistantPreview: null,
  artifact: {
    id: null,
    name: "",
    files: [],
    activeFile: null,
    dirty: false,
    treeCollapsed: false,
  },
  admin: {
    unavailable: false,
    scopes: [],
    scope: null,
    currentPath: "",
    entries: [],
    selectedEntry: null,
    activeFile: null,
    dirty: false,
  },
  selectedNodeId: null,
  selectedNodeIds: new Set(),
  hoveredNodeId: null,
  inlineLabelEditNodeId: null,
  selectedBoundedContextName: null,
  selectedConnectionId: null,
  boundedContextCreateMode: false,
  boundedContextDraftNodeIds: new Set(),
  boundedContextDraftName: "",
  boundedContextViewMode: "normal",
  activeBoundedContextName: "",
  dragBoundedContext: null,
  canvasFocusStack: [],
  impactMode: false,
  impactData: null,
  paletteCollapsed: false,
  paletteDragType: "",
  paletteSearch: {},
  paletteGroupCollapsed: {},
  leftPaneMode: "palette",
  guidedModeling: {
    definitions: {},
    endToEnd: null,
    progress: { completedTaskIds: [], activePhaseId: null },
    loading: false,
  },
  validation: {
    issues: [],
    inProgress: false,
    panelOpen: false,
    firstIssueShown: false,
    lastValidatedAt: null,
    issueView: "errors",
  },
  edgeKindPicker: {
    open: false,
    menuOpen: false,
    edgeId: null,
    drawnFromId: null,
    drawnToId: null,
    x: 0,
    y: 0,
    options: [],
  },
  undo: {
    modelReplacements: [],
    diagramHistory: {},
  },
};
